package net.shopin.ledger.po;

import java.util.Date;

public class LedgerContract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.id
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.settlement_status
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String settlementStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.cabinet_status
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    private String cabinetStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.cabinet_date
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    private Date cabinetDate;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.sign_mark
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String signMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.authorized_start_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Date authorizedStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.authorized_end_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Date authorizedEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.supplier_code
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String supplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.category
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.brand_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.store_encoding
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String storeEncoding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.store_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.deduction_rate
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Double deductionRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.assessment_indicator
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String assessmentIndicator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.signing_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Date signingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.start_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.end_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.contract_deadline
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Date contractDeadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.management_fees
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Double managementFees;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.card_fees
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String cardFees;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.contract_version
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String contractVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.check_tag
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String checkTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.check_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String checkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.check_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Date checkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.valid
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Boolean valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract.mark
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String mark;
    
    
    /**
     * @author lcl
     * 说明：补充协议字段
     */
    private String supplemental;

    
    public String getSupplemental() {
		return supplemental;
	}

	public void setSupplemental(String supplemental) {
		this.supplemental = supplemental;
	}

	private Integer parentId;
	
	private String clearType;
	
	private String clearThreshold;
	
	private String clearDeduction;

	private Boolean decorateRules;//商户装修守则
	
	private String area;//面积
	
	private String cooperationWay;
	
	private String bizContractVersion;
	
	private String brandLevel;
	
	public String getBrandLevel() {
		return brandLevel;
	}

	public void setBrandLevel(String brandLevel) {
		this.brandLevel = brandLevel;
	}

	public Integer getParentId() {
		return parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getClearType() {
		return clearType;
	}

	public void setClearType(String clearType) {
		this.clearType = clearType;
	}

	public String getClearThreshold() {
		return clearThreshold;
	}

	public void setClearThreshold(String clearThreshold) {
		this.clearThreshold = clearThreshold;
	}

	public String getClearDeduction() {
		return clearDeduction;
	}

	public void setClearDeduction(String clearDeduction) {
		this.clearDeduction = clearDeduction;
	}

	public Boolean getDecorateRules() {
		return decorateRules;
	}

	public void setDecorateRules(Boolean decorateRules) {
		this.decorateRules = decorateRules;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getCooperationWay() {
		return cooperationWay;
	}

	public void setCooperationWay(String cooperationWay) {
		this.cooperationWay = cooperationWay;
	}

	public String getBizContractVersion() {
		return bizContractVersion;
	}

	public void setBizContractVersion(String bizContractVersion) {
		this.bizContractVersion = bizContractVersion;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.id
     *
     * @return the value of ledger_contract.id
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.id
     *
     * @param id the value for ledger_contract.id
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.settlement_status
     *
     * @return the value of ledger_contract.settlement_status
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getSettlementStatus() {
        return settlementStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.settlement_status
     *
     * @param settlementStatus the value for ledger_contract.settlement_status
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setSettlementStatus(String settlementStatus) {
        this.settlementStatus = settlementStatus == null ? null : settlementStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.cabinet_status
     *
     * @return the value of ledger_contract.cabinet_status
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    public String getCabinetStatus() {
        return cabinetStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.cabinet_status
     *
     * @param cabinetStatus the value for ledger_contract.cabinet_status
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    public void setCabinetStatus(String cabinetStatus) {
        this.cabinetStatus = cabinetStatus == null ? null : cabinetStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.cabinet_date
     *
     * @return the value of ledger_contract.cabinet_date
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    public Date getCabinetDate() {
        return cabinetDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.cabinet_date
     *
     * @param cabinetDate the value for ledger_contract.cabinet_date
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    public void setCabinetDate(Date cabinetDate) {
        this.cabinetDate = cabinetDate;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.sign_mark
     *
     * @return the value of ledger_contract.sign_mark
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getSignMark() {
        return signMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.sign_mark
     *
     * @param signMark the value for ledger_contract.sign_mark
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setSignMark(String signMark) {
        this.signMark = signMark == null ? null : signMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.authorized_start_date
     *
     * @return the value of ledger_contract.authorized_start_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Date getAuthorizedStartDate() {
        return authorizedStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.authorized_start_date
     *
     * @param authorizedStartDate the value for ledger_contract.authorized_start_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setAuthorizedStartDate(Date authorizedStartDate) {
        this.authorizedStartDate = authorizedStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.authorized_end_date
     *
     * @return the value of ledger_contract.authorized_end_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Date getAuthorizedEndDate() {
        return authorizedEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.authorized_end_date
     *
     * @param authorizedEndDate the value for ledger_contract.authorized_end_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setAuthorizedEndDate(Date authorizedEndDate) {
        this.authorizedEndDate = authorizedEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.supplier_code
     *
     * @return the value of ledger_contract.supplier_code
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.supplier_code
     *
     * @param supplierCode the value for ledger_contract.supplier_code
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode == null ? null : supplierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.category
     *
     * @return the value of ledger_contract.category
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.category
     *
     * @param category the value for ledger_contract.category
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.brand_name
     *
     * @return the value of ledger_contract.brand_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.brand_name
     *
     * @param brandName the value for ledger_contract.brand_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.store_encoding
     *
     * @return the value of ledger_contract.store_encoding
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getStoreEncoding() {
        return storeEncoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.store_encoding
     *
     * @param storeEncoding the value for ledger_contract.store_encoding
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setStoreEncoding(String storeEncoding) {
        this.storeEncoding = storeEncoding == null ? null : storeEncoding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.store_name
     *
     * @return the value of ledger_contract.store_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.store_name
     *
     * @param storeName the value for ledger_contract.store_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.deduction_rate
     *
     * @return the value of ledger_contract.deduction_rate
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Double getDeductionRate() {
        return deductionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.deduction_rate
     *
     * @param deductionRate the value for ledger_contract.deduction_rate
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setDeductionRate(Double deductionRate) {
        this.deductionRate = deductionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.assessment_indicator
     *
     * @return the value of ledger_contract.assessment_indicator
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getAssessmentIndicator() {
        return assessmentIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.assessment_indicator
     *
     * @param assessmentIndicator the value for ledger_contract.assessment_indicator
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setAssessmentIndicator(String assessmentIndicator) {
        this.assessmentIndicator = assessmentIndicator == null ? null : assessmentIndicator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.signing_date
     *
     * @return the value of ledger_contract.signing_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Date getSigningDate() {
        return signingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.signing_date
     *
     * @param signingDate the value for ledger_contract.signing_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setSigningDate(Date signingDate) {
        this.signingDate = signingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.start_date
     *
     * @return the value of ledger_contract.start_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.start_date
     *
     * @param startDate the value for ledger_contract.start_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.end_date
     *
     * @return the value of ledger_contract.end_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.end_date
     *
     * @param endDate the value for ledger_contract.end_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.contract_deadline
     *
     * @return the value of ledger_contract.contract_deadline
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Date getContractDeadline() {
        return contractDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.contract_deadline
     *
     * @param contractDeadline the value for ledger_contract.contract_deadline
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setContractDeadline(Date contractDeadline) {
        this.contractDeadline = contractDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.management_fees
     *
     * @return the value of ledger_contract.management_fees
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Double getManagementFees() {
        return managementFees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.management_fees
     *
     * @param managementFees the value for ledger_contract.management_fees
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setManagementFees(Double managementFees) {
        this.managementFees = managementFees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.card_fees
     *
     * @return the value of ledger_contract.card_fees
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getCardFees() {
        return cardFees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.card_fees
     *
     * @param cardFees the value for ledger_contract.card_fees
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setCardFees(String cardFees) {
        this.cardFees = cardFees == null ? null : cardFees.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.contract_version
     *
     * @return the value of ledger_contract.contract_version
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getContractVersion() {
        return contractVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.contract_version
     *
     * @param contractVersion the value for ledger_contract.contract_version
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setContractVersion(String contractVersion) {
        this.contractVersion = contractVersion == null ? null : contractVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.check_tag
     *
     * @return the value of ledger_contract.check_tag
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getCheckTag() {
        return checkTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.check_tag
     *
     * @param checkTag the value for ledger_contract.check_tag
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setCheckTag(String checkTag) {
        this.checkTag = checkTag == null ? null : checkTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.check_name
     *
     * @return the value of ledger_contract.check_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getCheckName() {
        return checkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.check_name
     *
     * @param checkName the value for ledger_contract.check_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setCheckName(String checkName) {
        this.checkName = checkName == null ? null : checkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.check_date
     *
     * @return the value of ledger_contract.check_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Date getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.check_date
     *
     * @param checkDate the value for ledger_contract.check_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.valid
     *
     * @return the value of ledger_contract.valid
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.valid
     *
     * @param valid the value for ledger_contract.valid
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract.mark
     *
     * @return the value of ledger_contract.mark
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract.mark
     *
     * @param mark the value for ledger_contract.mark
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }
}