package net.shopin.ledger.po;

import java.util.Date;

public class LedgerContractSupplyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract_supply_info.id
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract_supply_info.supplier_code
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    private String supplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract_supply_info.supplier_name
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract_supply_info.legal_representative
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    private String legalRepresentative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract_supply_info.attorney
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    private String attorney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract_supply_info.mobile_phone1
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    private String mobilePhone1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract_supply_info.mobile_phone1_name
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    private String mobilePhone1Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract_supply_info.mobile_phone2
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    private String mobilePhone2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract_supply_info.mobile_phone2_name
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    private String mobilePhone2Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract_supply_info.fixed_telephone
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    private String fixedTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract_supply_info.fixed_telephone_name
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    private String fixedTelephoneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_contract_supply_info.basic_signing_date
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    private Date basicSigningDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract_supply_info.id
     *
     * @return the value of ledger_contract_supply_info.id
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract_supply_info.id
     *
     * @param id the value for ledger_contract_supply_info.id
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract_supply_info.supplier_code
     *
     * @return the value of ledger_contract_supply_info.supplier_code
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract_supply_info.supplier_code
     *
     * @param supplierCode the value for ledger_contract_supply_info.supplier_code
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode == null ? null : supplierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract_supply_info.supplier_name
     *
     * @return the value of ledger_contract_supply_info.supplier_name
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract_supply_info.supplier_name
     *
     * @param supplierName the value for ledger_contract_supply_info.supplier_name
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract_supply_info.legal_representative
     *
     * @return the value of ledger_contract_supply_info.legal_representative
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public String getLegalRepresentative() {
        return legalRepresentative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract_supply_info.legal_representative
     *
     * @param legalRepresentative the value for ledger_contract_supply_info.legal_representative
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public void setLegalRepresentative(String legalRepresentative) {
        this.legalRepresentative = legalRepresentative == null ? null : legalRepresentative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract_supply_info.attorney
     *
     * @return the value of ledger_contract_supply_info.attorney
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public String getAttorney() {
        return attorney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract_supply_info.attorney
     *
     * @param attorney the value for ledger_contract_supply_info.attorney
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public void setAttorney(String attorney) {
        this.attorney = attorney == null ? null : attorney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract_supply_info.mobile_phone1
     *
     * @return the value of ledger_contract_supply_info.mobile_phone1
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public String getMobilePhone1() {
        return mobilePhone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract_supply_info.mobile_phone1
     *
     * @param mobilePhone1 the value for ledger_contract_supply_info.mobile_phone1
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public void setMobilePhone1(String mobilePhone1) {
        this.mobilePhone1 = mobilePhone1 == null ? null : mobilePhone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract_supply_info.mobile_phone1_name
     *
     * @return the value of ledger_contract_supply_info.mobile_phone1_name
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public String getMobilePhone1Name() {
        return mobilePhone1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract_supply_info.mobile_phone1_name
     *
     * @param mobilePhone1Name the value for ledger_contract_supply_info.mobile_phone1_name
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public void setMobilePhone1Name(String mobilePhone1Name) {
        this.mobilePhone1Name = mobilePhone1Name == null ? null : mobilePhone1Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract_supply_info.mobile_phone2
     *
     * @return the value of ledger_contract_supply_info.mobile_phone2
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public String getMobilePhone2() {
        return mobilePhone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract_supply_info.mobile_phone2
     *
     * @param mobilePhone2 the value for ledger_contract_supply_info.mobile_phone2
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public void setMobilePhone2(String mobilePhone2) {
        this.mobilePhone2 = mobilePhone2 == null ? null : mobilePhone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract_supply_info.mobile_phone2_name
     *
     * @return the value of ledger_contract_supply_info.mobile_phone2_name
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public String getMobilePhone2Name() {
        return mobilePhone2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract_supply_info.mobile_phone2_name
     *
     * @param mobilePhone2Name the value for ledger_contract_supply_info.mobile_phone2_name
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public void setMobilePhone2Name(String mobilePhone2Name) {
        this.mobilePhone2Name = mobilePhone2Name == null ? null : mobilePhone2Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract_supply_info.fixed_telephone
     *
     * @return the value of ledger_contract_supply_info.fixed_telephone
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public String getFixedTelephone() {
        return fixedTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract_supply_info.fixed_telephone
     *
     * @param fixedTelephone the value for ledger_contract_supply_info.fixed_telephone
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public void setFixedTelephone(String fixedTelephone) {
        this.fixedTelephone = fixedTelephone == null ? null : fixedTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract_supply_info.fixed_telephone_name
     *
     * @return the value of ledger_contract_supply_info.fixed_telephone_name
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public String getFixedTelephoneName() {
        return fixedTelephoneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract_supply_info.fixed_telephone_name
     *
     * @param fixedTelephoneName the value for ledger_contract_supply_info.fixed_telephone_name
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public void setFixedTelephoneName(String fixedTelephoneName) {
        this.fixedTelephoneName = fixedTelephoneName == null ? null : fixedTelephoneName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_contract_supply_info.basic_signing_date
     *
     * @return the value of ledger_contract_supply_info.basic_signing_date
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public Date getBasicSigningDate() {
        return basicSigningDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_contract_supply_info.basic_signing_date
     *
     * @param basicSigningDate the value for ledger_contract_supply_info.basic_signing_date
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public void setBasicSigningDate(Date basicSigningDate) {
        this.basicSigningDate = basicSigningDate;
    }
}