package net.shopin.ledger.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class LedgerQualificationInspectionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ledger_qualification_inspection
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ledger_qualification_inspection
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ledger_qualification_inspection
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_inspection
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public LedgerQualificationInspectionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_inspection
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_inspection
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_inspection
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_inspection
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_inspection
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_inspection
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_inspection
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_inspection
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_inspection
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_inspection
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ledger_qualification_inspection
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLedgerQualificationIdIsNull() {
            addCriterion("ledger_qualification_id is null");
            return (Criteria) this;
        }

        public Criteria andLedgerQualificationIdIsNotNull() {
            addCriterion("ledger_qualification_id is not null");
            return (Criteria) this;
        }

        public Criteria andLedgerQualificationIdEqualTo(Integer value) {
            addCriterion("ledger_qualification_id =", value, "ledgerQualificationId");
            return (Criteria) this;
        }

        public Criteria andLedgerQualificationIdNotEqualTo(Integer value) {
            addCriterion("ledger_qualification_id <>", value, "ledgerQualificationId");
            return (Criteria) this;
        }

        public Criteria andLedgerQualificationIdGreaterThan(Integer value) {
            addCriterion("ledger_qualification_id >", value, "ledgerQualificationId");
            return (Criteria) this;
        }

        public Criteria andLedgerQualificationIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ledger_qualification_id >=", value, "ledgerQualificationId");
            return (Criteria) this;
        }

        public Criteria andLedgerQualificationIdLessThan(Integer value) {
            addCriterion("ledger_qualification_id <", value, "ledgerQualificationId");
            return (Criteria) this;
        }

        public Criteria andLedgerQualificationIdLessThanOrEqualTo(Integer value) {
            addCriterion("ledger_qualification_id <=", value, "ledgerQualificationId");
            return (Criteria) this;
        }

        public Criteria andLedgerQualificationIdIn(List<Integer> values) {
            addCriterion("ledger_qualification_id in", values, "ledgerQualificationId");
            return (Criteria) this;
        }

        public Criteria andLedgerQualificationIdNotIn(List<Integer> values) {
            addCriterion("ledger_qualification_id not in", values, "ledgerQualificationId");
            return (Criteria) this;
        }

        public Criteria andLedgerQualificationIdBetween(Integer value1, Integer value2) {
            addCriterion("ledger_qualification_id between", value1, value2, "ledgerQualificationId");
            return (Criteria) this;
        }

        public Criteria andLedgerQualificationIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ledger_qualification_id not between", value1, value2, "ledgerQualificationId");
            return (Criteria) this;
        }

        public Criteria andInspectionTypeIsNull() {
            addCriterion("inspection_type is null");
            return (Criteria) this;
        }

        public Criteria andInspectionTypeIsNotNull() {
            addCriterion("inspection_type is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionTypeEqualTo(String value) {
            addCriterion("inspection_type =", value, "inspectionType");
            return (Criteria) this;
        }

        public Criteria andInspectionTypeNotEqualTo(String value) {
            addCriterion("inspection_type <>", value, "inspectionType");
            return (Criteria) this;
        }

        public Criteria andInspectionTypeGreaterThan(String value) {
            addCriterion("inspection_type >", value, "inspectionType");
            return (Criteria) this;
        }

        public Criteria andInspectionTypeGreaterThanOrEqualTo(String value) {
            addCriterion("inspection_type >=", value, "inspectionType");
            return (Criteria) this;
        }

        public Criteria andInspectionTypeLessThan(String value) {
            addCriterion("inspection_type <", value, "inspectionType");
            return (Criteria) this;
        }

        public Criteria andInspectionTypeLessThanOrEqualTo(String value) {
            addCriterion("inspection_type <=", value, "inspectionType");
            return (Criteria) this;
        }

        public Criteria andInspectionTypeLike(String value) {
            addCriterion("inspection_type like", value, "inspectionType");
            return (Criteria) this;
        }

        public Criteria andInspectionTypeNotLike(String value) {
            addCriterion("inspection_type not like", value, "inspectionType");
            return (Criteria) this;
        }

        public Criteria andInspectionTypeIn(List<String> values) {
            addCriterion("inspection_type in", values, "inspectionType");
            return (Criteria) this;
        }

        public Criteria andInspectionTypeNotIn(List<String> values) {
            addCriterion("inspection_type not in", values, "inspectionType");
            return (Criteria) this;
        }

        public Criteria andInspectionTypeBetween(String value1, String value2) {
            addCriterion("inspection_type between", value1, value2, "inspectionType");
            return (Criteria) this;
        }

        public Criteria andInspectionTypeNotBetween(String value1, String value2) {
            addCriterion("inspection_type not between", value1, value2, "inspectionType");
            return (Criteria) this;
        }

        public Criteria andInspectionDateIsNull() {
            addCriterion("inspection_date is null");
            return (Criteria) this;
        }

        public Criteria andInspectionDateIsNotNull() {
            addCriterion("inspection_date is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionDateEqualTo(Date value) {
            addCriterionForJDBCDate("inspection_date =", value, "inspectionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("inspection_date <>", value, "inspectionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionDateGreaterThan(Date value) {
            addCriterionForJDBCDate("inspection_date >", value, "inspectionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("inspection_date >=", value, "inspectionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionDateLessThan(Date value) {
            addCriterionForJDBCDate("inspection_date <", value, "inspectionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("inspection_date <=", value, "inspectionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionDateIn(List<Date> values) {
            addCriterionForJDBCDate("inspection_date in", values, "inspectionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("inspection_date not in", values, "inspectionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("inspection_date between", value1, value2, "inspectionDate");
            return (Criteria) this;
        }

        public Criteria andInspectionDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("inspection_date not between", value1, value2, "inspectionDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ledger_qualification_inspection
     *
     * @mbggenerated do_not_delete_during_merge Thu Oct 08 09:52:10 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ledger_qualification_inspection
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}