package net.shopin.ledger.po;

import java.util.ArrayList;
import java.util.List;

public class LedgerQualificationSupplyInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ledger_qualification_supply_info
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ledger_qualification_supply_info
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ledger_qualification_supply_info
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_supply_info
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public LedgerQualificationSupplyInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_supply_info
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_supply_info
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_supply_info
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_supply_info
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_supply_info
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_supply_info
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_supply_info
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_supply_info
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_supply_info
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_qualification_supply_info
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ledger_qualification_supply_info
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeIsNull() {
            addCriterion("supplier_code is null");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeIsNotNull() {
            addCriterion("supplier_code is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeEqualTo(String value) {
            addCriterion("supplier_code =", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeNotEqualTo(String value) {
            addCriterion("supplier_code <>", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeGreaterThan(String value) {
            addCriterion("supplier_code >", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeGreaterThanOrEqualTo(String value) {
            addCriterion("supplier_code >=", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeLessThan(String value) {
            addCriterion("supplier_code <", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeLessThanOrEqualTo(String value) {
            addCriterion("supplier_code <=", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeLike(String value) {
            addCriterion("supplier_code like", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeNotLike(String value) {
            addCriterion("supplier_code not like", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeIn(List<String> values) {
            addCriterion("supplier_code in", values, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeNotIn(List<String> values) {
            addCriterion("supplier_code not in", values, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeBetween(String value1, String value2) {
            addCriterion("supplier_code between", value1, value2, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeNotBetween(String value1, String value2) {
            addCriterion("supplier_code not between", value1, value2, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierNameIsNull() {
            addCriterion("supplier_name is null");
            return (Criteria) this;
        }

        public Criteria andSupplierNameIsNotNull() {
            addCriterion("supplier_name is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierNameEqualTo(String value) {
            addCriterion("supplier_name =", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameNotEqualTo(String value) {
            addCriterion("supplier_name <>", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameGreaterThan(String value) {
            addCriterion("supplier_name >", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameGreaterThanOrEqualTo(String value) {
            addCriterion("supplier_name >=", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameLessThan(String value) {
            addCriterion("supplier_name <", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameLessThanOrEqualTo(String value) {
            addCriterion("supplier_name <=", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameLike(String value) {
            addCriterion("supplier_name like", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameNotLike(String value) {
            addCriterion("supplier_name not like", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameIn(List<String> values) {
            addCriterion("supplier_name in", values, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameNotIn(List<String> values) {
            addCriterion("supplier_name not in", values, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameBetween(String value1, String value2) {
            addCriterion("supplier_name between", value1, value2, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameNotBetween(String value1, String value2) {
            addCriterion("supplier_name not between", value1, value2, "supplierName");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseIsNull() {
            addCriterion("business_license is null");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseIsNotNull() {
            addCriterion("business_license is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseEqualTo(String value) {
            addCriterion("business_license =", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseNotEqualTo(String value) {
            addCriterion("business_license <>", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseGreaterThan(String value) {
            addCriterion("business_license >", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseGreaterThanOrEqualTo(String value) {
            addCriterion("business_license >=", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseLessThan(String value) {
            addCriterion("business_license <", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseLessThanOrEqualTo(String value) {
            addCriterion("business_license <=", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseLike(String value) {
            addCriterion("business_license like", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseNotLike(String value) {
            addCriterion("business_license not like", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseIn(List<String> values) {
            addCriterion("business_license in", values, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseNotIn(List<String> values) {
            addCriterion("business_license not in", values, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseBetween(String value1, String value2) {
            addCriterion("business_license between", value1, value2, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseNotBetween(String value1, String value2) {
            addCriterion("business_license not between", value1, value2, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andNationalTaxRegistrationIsNull() {
            addCriterion("national_tax_registration is null");
            return (Criteria) this;
        }

        public Criteria andNationalTaxRegistrationIsNotNull() {
            addCriterion("national_tax_registration is not null");
            return (Criteria) this;
        }

        public Criteria andNationalTaxRegistrationEqualTo(Boolean value) {
            addCriterion("national_tax_registration =", value, "nationalTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andNationalTaxRegistrationNotEqualTo(Boolean value) {
            addCriterion("national_tax_registration <>", value, "nationalTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andNationalTaxRegistrationGreaterThan(Boolean value) {
            addCriterion("national_tax_registration >", value, "nationalTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andNationalTaxRegistrationGreaterThanOrEqualTo(Boolean value) {
            addCriterion("national_tax_registration >=", value, "nationalTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andNationalTaxRegistrationLessThan(Boolean value) {
            addCriterion("national_tax_registration <", value, "nationalTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andNationalTaxRegistrationLessThanOrEqualTo(Boolean value) {
            addCriterion("national_tax_registration <=", value, "nationalTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andNationalTaxRegistrationIn(List<Boolean> values) {
            addCriterion("national_tax_registration in", values, "nationalTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andNationalTaxRegistrationNotIn(List<Boolean> values) {
            addCriterion("national_tax_registration not in", values, "nationalTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andNationalTaxRegistrationBetween(Boolean value1, Boolean value2) {
            addCriterion("national_tax_registration between", value1, value2, "nationalTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andNationalTaxRegistrationNotBetween(Boolean value1, Boolean value2) {
            addCriterion("national_tax_registration not between", value1, value2, "nationalTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andLandTaxRegistrationIsNull() {
            addCriterion("land_tax_registration is null");
            return (Criteria) this;
        }

        public Criteria andLandTaxRegistrationIsNotNull() {
            addCriterion("land_tax_registration is not null");
            return (Criteria) this;
        }

        public Criteria andLandTaxRegistrationEqualTo(Boolean value) {
            addCriterion("land_tax_registration =", value, "landTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andLandTaxRegistrationNotEqualTo(Boolean value) {
            addCriterion("land_tax_registration <>", value, "landTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andLandTaxRegistrationGreaterThan(Boolean value) {
            addCriterion("land_tax_registration >", value, "landTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andLandTaxRegistrationGreaterThanOrEqualTo(Boolean value) {
            addCriterion("land_tax_registration >=", value, "landTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andLandTaxRegistrationLessThan(Boolean value) {
            addCriterion("land_tax_registration <", value, "landTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andLandTaxRegistrationLessThanOrEqualTo(Boolean value) {
            addCriterion("land_tax_registration <=", value, "landTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andLandTaxRegistrationIn(List<Boolean> values) {
            addCriterion("land_tax_registration in", values, "landTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andLandTaxRegistrationNotIn(List<Boolean> values) {
            addCriterion("land_tax_registration not in", values, "landTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andLandTaxRegistrationBetween(Boolean value1, Boolean value2) {
            addCriterion("land_tax_registration between", value1, value2, "landTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andLandTaxRegistrationNotBetween(Boolean value1, Boolean value2) {
            addCriterion("land_tax_registration not between", value1, value2, "landTaxRegistration");
            return (Criteria) this;
        }

        public Criteria andGeneralTaxpayerIsNull() {
            addCriterion("general_taxpayer is null");
            return (Criteria) this;
        }

        public Criteria andGeneralTaxpayerIsNotNull() {
            addCriterion("general_taxpayer is not null");
            return (Criteria) this;
        }

        public Criteria andGeneralTaxpayerEqualTo(String value) {
            addCriterion("general_taxpayer =", value, "generalTaxpayer");
            return (Criteria) this;
        }

        public Criteria andGeneralTaxpayerNotEqualTo(String value) {
            addCriterion("general_taxpayer <>", value, "generalTaxpayer");
            return (Criteria) this;
        }

        public Criteria andGeneralTaxpayerGreaterThan(String value) {
            addCriterion("general_taxpayer >", value, "generalTaxpayer");
            return (Criteria) this;
        }

        public Criteria andGeneralTaxpayerGreaterThanOrEqualTo(String value) {
            addCriterion("general_taxpayer >=", value, "generalTaxpayer");
            return (Criteria) this;
        }

        public Criteria andGeneralTaxpayerLessThan(String value) {
            addCriterion("general_taxpayer <", value, "generalTaxpayer");
            return (Criteria) this;
        }

        public Criteria andGeneralTaxpayerLessThanOrEqualTo(String value) {
            addCriterion("general_taxpayer <=", value, "generalTaxpayer");
            return (Criteria) this;
        }

        public Criteria andGeneralTaxpayerLike(String value) {
            addCriterion("general_taxpayer like", value, "generalTaxpayer");
            return (Criteria) this;
        }

        public Criteria andGeneralTaxpayerNotLike(String value) {
            addCriterion("general_taxpayer not like", value, "generalTaxpayer");
            return (Criteria) this;
        }

        public Criteria andGeneralTaxpayerIn(List<String> values) {
            addCriterion("general_taxpayer in", values, "generalTaxpayer");
            return (Criteria) this;
        }

        public Criteria andGeneralTaxpayerNotIn(List<String> values) {
            addCriterion("general_taxpayer not in", values, "generalTaxpayer");
            return (Criteria) this;
        }

        public Criteria andGeneralTaxpayerBetween(String value1, String value2) {
            addCriterion("general_taxpayer between", value1, value2, "generalTaxpayer");
            return (Criteria) this;
        }

        public Criteria andGeneralTaxpayerNotBetween(String value1, String value2) {
            addCriterion("general_taxpayer not between", value1, value2, "generalTaxpayer");
            return (Criteria) this;
        }

        public Criteria andIsblacklistIsNull() {
            addCriterion("isblacklist is null");
            return (Criteria) this;
        }

        public Criteria andIsblacklistIsNotNull() {
            addCriterion("isblacklist is not null");
            return (Criteria) this;
        }

        public Criteria andIsblacklistEqualTo(Boolean value) {
            addCriterion("isblacklist =", value, "isblacklist");
            return (Criteria) this;
        }

        public Criteria andIsblacklistNotEqualTo(Boolean value) {
            addCriterion("isblacklist <>", value, "isblacklist");
            return (Criteria) this;
        }

        public Criteria andIsblacklistGreaterThan(Boolean value) {
            addCriterion("isblacklist >", value, "isblacklist");
            return (Criteria) this;
        }

        public Criteria andIsblacklistGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isblacklist >=", value, "isblacklist");
            return (Criteria) this;
        }

        public Criteria andIsblacklistLessThan(Boolean value) {
            addCriterion("isblacklist <", value, "isblacklist");
            return (Criteria) this;
        }

        public Criteria andIsblacklistLessThanOrEqualTo(Boolean value) {
            addCriterion("isblacklist <=", value, "isblacklist");
            return (Criteria) this;
        }

        public Criteria andIsblacklistIn(List<Boolean> values) {
            addCriterion("isblacklist in", values, "isblacklist");
            return (Criteria) this;
        }

        public Criteria andIsblacklistNotIn(List<Boolean> values) {
            addCriterion("isblacklist not in", values, "isblacklist");
            return (Criteria) this;
        }

        public Criteria andIsblacklistBetween(Boolean value1, Boolean value2) {
            addCriterion("isblacklist between", value1, value2, "isblacklist");
            return (Criteria) this;
        }

        public Criteria andIsblacklistNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isblacklist not between", value1, value2, "isblacklist");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ledger_qualification_supply_info
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 18 14:28:12 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ledger_qualification_supply_info
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}