package net.shopin.ledger.po;

public class LedgerQualificationSupplyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification_supply_info.id
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification_supply_info.supplier_code
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String supplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification_supply_info.supplier_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification_supply_info.business_license
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String businessLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification_supply_info.national_tax_registration
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Boolean nationalTaxRegistration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification_supply_info.land_tax_registration
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Boolean landTaxRegistration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification_supply_info.general_taxpayer
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String generalTaxpayer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification_supply_info.isblacklist
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Boolean isblacklist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification_supply_info.id
     *
     * @return the value of ledger_qualification_supply_info.id
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification_supply_info.id
     *
     * @param id the value for ledger_qualification_supply_info.id
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification_supply_info.supplier_code
     *
     * @return the value of ledger_qualification_supply_info.supplier_code
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification_supply_info.supplier_code
     *
     * @param supplierCode the value for ledger_qualification_supply_info.supplier_code
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode == null ? null : supplierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification_supply_info.supplier_name
     *
     * @return the value of ledger_qualification_supply_info.supplier_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification_supply_info.supplier_name
     *
     * @param supplierName the value for ledger_qualification_supply_info.supplier_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification_supply_info.business_license
     *
     * @return the value of ledger_qualification_supply_info.business_license
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getBusinessLicense() {
        return businessLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification_supply_info.business_license
     *
     * @param businessLicense the value for ledger_qualification_supply_info.business_license
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setBusinessLicense(String businessLicense) {
        this.businessLicense = businessLicense == null ? null : businessLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification_supply_info.national_tax_registration
     *
     * @return the value of ledger_qualification_supply_info.national_tax_registration
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Boolean getNationalTaxRegistration() {
        return nationalTaxRegistration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification_supply_info.national_tax_registration
     *
     * @param nationalTaxRegistration the value for ledger_qualification_supply_info.national_tax_registration
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setNationalTaxRegistration(Boolean nationalTaxRegistration) {
        this.nationalTaxRegistration = nationalTaxRegistration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification_supply_info.land_tax_registration
     *
     * @return the value of ledger_qualification_supply_info.land_tax_registration
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Boolean getLandTaxRegistration() {
        return landTaxRegistration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification_supply_info.land_tax_registration
     *
     * @param landTaxRegistration the value for ledger_qualification_supply_info.land_tax_registration
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setLandTaxRegistration(Boolean landTaxRegistration) {
        this.landTaxRegistration = landTaxRegistration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification_supply_info.general_taxpayer
     *
     * @return the value of ledger_qualification_supply_info.general_taxpayer
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getGeneralTaxpayer() {
        return generalTaxpayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification_supply_info.general_taxpayer
     *
     * @param generalTaxpayer the value for ledger_qualification_supply_info.general_taxpayer
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setGeneralTaxpayer(String generalTaxpayer) {
        this.generalTaxpayer = generalTaxpayer == null ? null : generalTaxpayer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification_supply_info.isblacklist
     *
     * @return the value of ledger_qualification_supply_info.isblacklist
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Boolean getIsblacklist() {
        return isblacklist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification_supply_info.isblacklist
     *
     * @param isblacklist the value for ledger_qualification_supply_info.isblacklist
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setIsblacklist(Boolean isblacklist) {
        this.isblacklist = isblacklist;
    }
}