package net.shopin.ledger.po;

public class LedgerQualificationWithBLOBs extends LedgerQualification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.single_store_authorization
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String singleStoreAuthorization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.description_problem
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String descriptionProblem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.mark
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.single_store_authorization
     *
     * @return the value of ledger_qualification.single_store_authorization
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getSingleStoreAuthorization() {
        return singleStoreAuthorization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.single_store_authorization
     *
     * @param singleStoreAuthorization the value for ledger_qualification.single_store_authorization
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setSingleStoreAuthorization(String singleStoreAuthorization) {
        this.singleStoreAuthorization = singleStoreAuthorization == null ? null : singleStoreAuthorization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.description_problem
     *
     * @return the value of ledger_qualification.description_problem
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getDescriptionProblem() {
        return descriptionProblem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.description_problem
     *
     * @param descriptionProblem the value for ledger_qualification.description_problem
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setDescriptionProblem(String descriptionProblem) {
        this.descriptionProblem = descriptionProblem == null ? null : descriptionProblem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.mark
     *
     * @return the value of ledger_qualification.mark
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.mark
     *
     * @param mark the value for ledger_qualification.mark
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }
}