package net.shopin.ledger.po;

import java.util.Date;

public class LedgerQualification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.id
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.expiration_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Date expirationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.status
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.mobile_phone1
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String mobilePhone1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.mobile_phone1_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String mobilePhone1Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.mobile_phone2
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String mobilePhone2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.mobile_phone2_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String mobilePhone2Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.fixed_telephone
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String fixedTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.fixed_telephone_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String fixedTelephoneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.brand_level
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String brandLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.supplier_code
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String supplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.category
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.brand_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.registration_number
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String registrationNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.approved_category
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String approvedCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.end_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.application_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Date applicationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.trademark_holder_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String trademarkHolderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.certificate_type
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String certificateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.certificate_number
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String certificateNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.acting_level
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String actingLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.first_proxy_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Date firstProxyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.first_proxy_annotation
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String firstProxyAnnotation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.second_proxy_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Date secondProxyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.second_proxy_annotation
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String secondProxyAnnotation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.third_proxy_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Date thirdProxyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.third_proxy_annotation
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String thirdProxyAnnotation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.forth_proxy_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Date forthProxyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.forth_proxy_annotation
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String forthProxyAnnotation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.fifth_proxy_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Date fifthProxyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.fifth_proxy_annotation
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String fifthProxyAnnotation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.declaration
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String declaration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.information_maintenance_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Date informationMaintenanceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.information_maintenance_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String informationMaintenanceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.approval_status
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String approvalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.review_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Date reviewDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.review_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private String reviewName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification.valid
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    private Boolean valid;

    private Date sixthProxyDate;
    
    private String sixthProxyAnnotation;
    
    public Date getSixthProxyDate() {
		return sixthProxyDate;
	}

	public void setSixthProxyDate(Date sixthProxyDate) {
		this.sixthProxyDate = sixthProxyDate;
	}

	public String getSixthProxyAnnotation() {
		return sixthProxyAnnotation;
	}

	public void setSixthProxyAnnotation(String sixthProxyAnnotation) {
		this.sixthProxyAnnotation = sixthProxyAnnotation;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.id
     *
     * @return the value of ledger_qualification.id
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.id
     *
     * @param id the value for ledger_qualification.id
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.expiration_date
     *
     * @return the value of ledger_qualification.expiration_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Date getExpirationDate() {
        return expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.expiration_date
     *
     * @param expirationDate the value for ledger_qualification.expiration_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.status
     *
     * @return the value of ledger_qualification.status
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.status
     *
     * @param status the value for ledger_qualification.status
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.mobile_phone1
     *
     * @return the value of ledger_qualification.mobile_phone1
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getMobilePhone1() {
        return mobilePhone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.mobile_phone1
     *
     * @param mobilePhone1 the value for ledger_qualification.mobile_phone1
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setMobilePhone1(String mobilePhone1) {
        this.mobilePhone1 = mobilePhone1 == null ? null : mobilePhone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.mobile_phone1_name
     *
     * @return the value of ledger_qualification.mobile_phone1_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getMobilePhone1Name() {
        return mobilePhone1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.mobile_phone1_name
     *
     * @param mobilePhone1Name the value for ledger_qualification.mobile_phone1_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setMobilePhone1Name(String mobilePhone1Name) {
        this.mobilePhone1Name = mobilePhone1Name == null ? null : mobilePhone1Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.mobile_phone2
     *
     * @return the value of ledger_qualification.mobile_phone2
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getMobilePhone2() {
        return mobilePhone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.mobile_phone2
     *
     * @param mobilePhone2 the value for ledger_qualification.mobile_phone2
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setMobilePhone2(String mobilePhone2) {
        this.mobilePhone2 = mobilePhone2 == null ? null : mobilePhone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.mobile_phone2_name
     *
     * @return the value of ledger_qualification.mobile_phone2_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getMobilePhone2Name() {
        return mobilePhone2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.mobile_phone2_name
     *
     * @param mobilePhone2Name the value for ledger_qualification.mobile_phone2_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setMobilePhone2Name(String mobilePhone2Name) {
        this.mobilePhone2Name = mobilePhone2Name == null ? null : mobilePhone2Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.fixed_telephone
     *
     * @return the value of ledger_qualification.fixed_telephone
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getFixedTelephone() {
        return fixedTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.fixed_telephone
     *
     * @param fixedTelephone the value for ledger_qualification.fixed_telephone
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setFixedTelephone(String fixedTelephone) {
        this.fixedTelephone = fixedTelephone == null ? null : fixedTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.fixed_telephone_name
     *
     * @return the value of ledger_qualification.fixed_telephone_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getFixedTelephoneName() {
        return fixedTelephoneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.fixed_telephone_name
     *
     * @param fixedTelephoneName the value for ledger_qualification.fixed_telephone_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setFixedTelephoneName(String fixedTelephoneName) {
        this.fixedTelephoneName = fixedTelephoneName == null ? null : fixedTelephoneName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.brand_level
     *
     * @return the value of ledger_qualification.brand_level
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getBrandLevel() {
        return brandLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.brand_level
     *
     * @param brandLevel the value for ledger_qualification.brand_level
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setBrandLevel(String brandLevel) {
        this.brandLevel = brandLevel == null ? null : brandLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.supplier_code
     *
     * @return the value of ledger_qualification.supplier_code
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.supplier_code
     *
     * @param supplierCode the value for ledger_qualification.supplier_code
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode == null ? null : supplierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.category
     *
     * @return the value of ledger_qualification.category
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.category
     *
     * @param category the value for ledger_qualification.category
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.brand_name
     *
     * @return the value of ledger_qualification.brand_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.brand_name
     *
     * @param brandName the value for ledger_qualification.brand_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.registration_number
     *
     * @return the value of ledger_qualification.registration_number
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getRegistrationNumber() {
        return registrationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.registration_number
     *
     * @param registrationNumber the value for ledger_qualification.registration_number
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber == null ? null : registrationNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.approved_category
     *
     * @return the value of ledger_qualification.approved_category
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getApprovedCategory() {
        return approvedCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.approved_category
     *
     * @param approvedCategory the value for ledger_qualification.approved_category
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setApprovedCategory(String approvedCategory) {
        this.approvedCategory = approvedCategory == null ? null : approvedCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.end_date
     *
     * @return the value of ledger_qualification.end_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.end_date
     *
     * @param endDate the value for ledger_qualification.end_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.application_date
     *
     * @return the value of ledger_qualification.application_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Date getApplicationDate() {
        return applicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.application_date
     *
     * @param applicationDate the value for ledger_qualification.application_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setApplicationDate(Date applicationDate) {
        this.applicationDate = applicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.trademark_holder_name
     *
     * @return the value of ledger_qualification.trademark_holder_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getTrademarkHolderName() {
        return trademarkHolderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.trademark_holder_name
     *
     * @param trademarkHolderName the value for ledger_qualification.trademark_holder_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setTrademarkHolderName(String trademarkHolderName) {
        this.trademarkHolderName = trademarkHolderName == null ? null : trademarkHolderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.certificate_type
     *
     * @return the value of ledger_qualification.certificate_type
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getCertificateType() {
        return certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.certificate_type
     *
     * @param certificateType the value for ledger_qualification.certificate_type
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setCertificateType(String certificateType) {
        this.certificateType = certificateType == null ? null : certificateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.certificate_number
     *
     * @return the value of ledger_qualification.certificate_number
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getCertificateNumber() {
        return certificateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.certificate_number
     *
     * @param certificateNumber the value for ledger_qualification.certificate_number
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setCertificateNumber(String certificateNumber) {
        this.certificateNumber = certificateNumber == null ? null : certificateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.acting_level
     *
     * @return the value of ledger_qualification.acting_level
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getActingLevel() {
        return actingLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.acting_level
     *
     * @param actingLevel the value for ledger_qualification.acting_level
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setActingLevel(String actingLevel) {
        this.actingLevel = actingLevel == null ? null : actingLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.first_proxy_date
     *
     * @return the value of ledger_qualification.first_proxy_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Date getFirstProxyDate() {
        return firstProxyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.first_proxy_date
     *
     * @param firstProxyDate the value for ledger_qualification.first_proxy_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setFirstProxyDate(Date firstProxyDate) {
        this.firstProxyDate = firstProxyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.first_proxy_annotation
     *
     * @return the value of ledger_qualification.first_proxy_annotation
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getFirstProxyAnnotation() {
        return firstProxyAnnotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.first_proxy_annotation
     *
     * @param firstProxyAnnotation the value for ledger_qualification.first_proxy_annotation
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setFirstProxyAnnotation(String firstProxyAnnotation) {
        this.firstProxyAnnotation = firstProxyAnnotation == null ? null : firstProxyAnnotation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.second_proxy_date
     *
     * @return the value of ledger_qualification.second_proxy_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Date getSecondProxyDate() {
        return secondProxyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.second_proxy_date
     *
     * @param secondProxyDate the value for ledger_qualification.second_proxy_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setSecondProxyDate(Date secondProxyDate) {
        this.secondProxyDate = secondProxyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.second_proxy_annotation
     *
     * @return the value of ledger_qualification.second_proxy_annotation
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getSecondProxyAnnotation() {
        return secondProxyAnnotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.second_proxy_annotation
     *
     * @param secondProxyAnnotation the value for ledger_qualification.second_proxy_annotation
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setSecondProxyAnnotation(String secondProxyAnnotation) {
        this.secondProxyAnnotation = secondProxyAnnotation == null ? null : secondProxyAnnotation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.third_proxy_date
     *
     * @return the value of ledger_qualification.third_proxy_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Date getThirdProxyDate() {
        return thirdProxyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.third_proxy_date
     *
     * @param thirdProxyDate the value for ledger_qualification.third_proxy_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setThirdProxyDate(Date thirdProxyDate) {
        this.thirdProxyDate = thirdProxyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.third_proxy_annotation
     *
     * @return the value of ledger_qualification.third_proxy_annotation
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getThirdProxyAnnotation() {
        return thirdProxyAnnotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.third_proxy_annotation
     *
     * @param thirdProxyAnnotation the value for ledger_qualification.third_proxy_annotation
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setThirdProxyAnnotation(String thirdProxyAnnotation) {
        this.thirdProxyAnnotation = thirdProxyAnnotation == null ? null : thirdProxyAnnotation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.forth_proxy_date
     *
     * @return the value of ledger_qualification.forth_proxy_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Date getForthProxyDate() {
        return forthProxyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.forth_proxy_date
     *
     * @param forthProxyDate the value for ledger_qualification.forth_proxy_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setForthProxyDate(Date forthProxyDate) {
        this.forthProxyDate = forthProxyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.forth_proxy_annotation
     *
     * @return the value of ledger_qualification.forth_proxy_annotation
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getForthProxyAnnotation() {
        return forthProxyAnnotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.forth_proxy_annotation
     *
     * @param forthProxyAnnotation the value for ledger_qualification.forth_proxy_annotation
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setForthProxyAnnotation(String forthProxyAnnotation) {
        this.forthProxyAnnotation = forthProxyAnnotation == null ? null : forthProxyAnnotation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.fifth_proxy_date
     *
     * @return the value of ledger_qualification.fifth_proxy_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Date getFifthProxyDate() {
        return fifthProxyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.fifth_proxy_date
     *
     * @param fifthProxyDate the value for ledger_qualification.fifth_proxy_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setFifthProxyDate(Date fifthProxyDate) {
        this.fifthProxyDate = fifthProxyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.fifth_proxy_annotation
     *
     * @return the value of ledger_qualification.fifth_proxy_annotation
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getFifthProxyAnnotation() {
        return fifthProxyAnnotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.fifth_proxy_annotation
     *
     * @param fifthProxyAnnotation the value for ledger_qualification.fifth_proxy_annotation
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setFifthProxyAnnotation(String fifthProxyAnnotation) {
        this.fifthProxyAnnotation = fifthProxyAnnotation == null ? null : fifthProxyAnnotation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.declaration
     *
     * @return the value of ledger_qualification.declaration
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getDeclaration() {
        return declaration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.declaration
     *
     * @param declaration the value for ledger_qualification.declaration
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setDeclaration(String declaration) {
        this.declaration = declaration == null ? null : declaration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.information_maintenance_date
     *
     * @return the value of ledger_qualification.information_maintenance_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Date getInformationMaintenanceDate() {
        return informationMaintenanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.information_maintenance_date
     *
     * @param informationMaintenanceDate the value for ledger_qualification.information_maintenance_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setInformationMaintenanceDate(Date informationMaintenanceDate) {
        this.informationMaintenanceDate = informationMaintenanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.information_maintenance_name
     *
     * @return the value of ledger_qualification.information_maintenance_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getInformationMaintenanceName() {
        return informationMaintenanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.information_maintenance_name
     *
     * @param informationMaintenanceName the value for ledger_qualification.information_maintenance_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setInformationMaintenanceName(String informationMaintenanceName) {
        this.informationMaintenanceName = informationMaintenanceName == null ? null : informationMaintenanceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.approval_status
     *
     * @return the value of ledger_qualification.approval_status
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getApprovalStatus() {
        return approvalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.approval_status
     *
     * @param approvalStatus the value for ledger_qualification.approval_status
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setApprovalStatus(String approvalStatus) {
        this.approvalStatus = approvalStatus == null ? null : approvalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.review_date
     *
     * @return the value of ledger_qualification.review_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Date getReviewDate() {
        return reviewDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.review_date
     *
     * @param reviewDate the value for ledger_qualification.review_date
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setReviewDate(Date reviewDate) {
        this.reviewDate = reviewDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.review_name
     *
     * @return the value of ledger_qualification.review_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public String getReviewName() {
        return reviewName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.review_name
     *
     * @param reviewName the value for ledger_qualification.review_name
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setReviewName(String reviewName) {
        this.reviewName = reviewName == null ? null : reviewName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification.valid
     *
     * @return the value of ledger_qualification.valid
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification.valid
     *
     * @param valid the value for ledger_qualification.valid
     *
     * @mbggenerated Fri Sep 18 14:28:12 CST 2015
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}