package net.shopin.ledger.po;

import java.util.Date;

public class LedgerQualificationInspection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification_inspection.id
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification_inspection.ledger_qualification_id
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    private Integer ledgerQualificationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification_inspection.inspection_type
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    private String inspectionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification_inspection.inspection_date
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    private Date inspectionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger_qualification_inspection.inspection_content
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    private String inspectionContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification_inspection.id
     *
     * @return the value of ledger_qualification_inspection.id
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification_inspection.id
     *
     * @param id the value for ledger_qualification_inspection.id
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification_inspection.ledger_qualification_id
     *
     * @return the value of ledger_qualification_inspection.ledger_qualification_id
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public Integer getLedgerQualificationId() {
        return ledgerQualificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification_inspection.ledger_qualification_id
     *
     * @param ledgerQualificationId the value for ledger_qualification_inspection.ledger_qualification_id
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public void setLedgerQualificationId(Integer ledgerQualificationId) {
        this.ledgerQualificationId = ledgerQualificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification_inspection.inspection_type
     *
     * @return the value of ledger_qualification_inspection.inspection_type
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public String getInspectionType() {
        return inspectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification_inspection.inspection_type
     *
     * @param inspectionType the value for ledger_qualification_inspection.inspection_type
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public void setInspectionType(String inspectionType) {
        this.inspectionType = inspectionType == null ? null : inspectionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification_inspection.inspection_date
     *
     * @return the value of ledger_qualification_inspection.inspection_date
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public Date getInspectionDate() {
        return inspectionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification_inspection.inspection_date
     *
     * @param inspectionDate the value for ledger_qualification_inspection.inspection_date
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public void setInspectionDate(Date inspectionDate) {
        this.inspectionDate = inspectionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger_qualification_inspection.inspection_content
     *
     * @return the value of ledger_qualification_inspection.inspection_content
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public String getInspectionContent() {
        return inspectionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger_qualification_inspection.inspection_content
     *
     * @param inspectionContent the value for ledger_qualification_inspection.inspection_content
     *
     * @mbggenerated Thu Oct 08 09:52:10 CST 2015
     */
    public void setInspectionContent(String inspectionContent) {
        this.inspectionContent = inspectionContent == null ? null : inspectionContent.trim();
    }
}