package net.shopin.ledger.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class LedgerContractSupplyInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ledger_contract_supply_info
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ledger_contract_supply_info
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ledger_contract_supply_info
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract_supply_info
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public LedgerContractSupplyInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract_supply_info
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract_supply_info
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract_supply_info
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract_supply_info
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract_supply_info
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract_supply_info
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract_supply_info
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract_supply_info
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract_supply_info
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract_supply_info
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ledger_contract_supply_info
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeIsNull() {
            addCriterion("supplier_code is null");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeIsNotNull() {
            addCriterion("supplier_code is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeEqualTo(String value) {
            addCriterion("supplier_code =", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeNotEqualTo(String value) {
            addCriterion("supplier_code <>", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeGreaterThan(String value) {
            addCriterion("supplier_code >", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeGreaterThanOrEqualTo(String value) {
            addCriterion("supplier_code >=", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeLessThan(String value) {
            addCriterion("supplier_code <", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeLessThanOrEqualTo(String value) {
            addCriterion("supplier_code <=", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeLike(String value) {
            addCriterion("supplier_code like", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeNotLike(String value) {
            addCriterion("supplier_code not like", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeIn(List<String> values) {
            addCriterion("supplier_code in", values, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeNotIn(List<String> values) {
            addCriterion("supplier_code not in", values, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeBetween(String value1, String value2) {
            addCriterion("supplier_code between", value1, value2, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeNotBetween(String value1, String value2) {
            addCriterion("supplier_code not between", value1, value2, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierNameIsNull() {
            addCriterion("supplier_name is null");
            return (Criteria) this;
        }

        public Criteria andSupplierNameIsNotNull() {
            addCriterion("supplier_name is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierNameEqualTo(String value) {
            addCriterion("supplier_name =", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameNotEqualTo(String value) {
            addCriterion("supplier_name <>", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameGreaterThan(String value) {
            addCriterion("supplier_name >", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameGreaterThanOrEqualTo(String value) {
            addCriterion("supplier_name >=", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameLessThan(String value) {
            addCriterion("supplier_name <", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameLessThanOrEqualTo(String value) {
            addCriterion("supplier_name <=", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameLike(String value) {
            addCriterion("supplier_name like", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameNotLike(String value) {
            addCriterion("supplier_name not like", value, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameIn(List<String> values) {
            addCriterion("supplier_name in", values, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameNotIn(List<String> values) {
            addCriterion("supplier_name not in", values, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameBetween(String value1, String value2) {
            addCriterion("supplier_name between", value1, value2, "supplierName");
            return (Criteria) this;
        }

        public Criteria andSupplierNameNotBetween(String value1, String value2) {
            addCriterion("supplier_name not between", value1, value2, "supplierName");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeIsNull() {
            addCriterion("legal_representative is null");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeIsNotNull() {
            addCriterion("legal_representative is not null");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeEqualTo(String value) {
            addCriterion("legal_representative =", value, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeNotEqualTo(String value) {
            addCriterion("legal_representative <>", value, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeGreaterThan(String value) {
            addCriterion("legal_representative >", value, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeGreaterThanOrEqualTo(String value) {
            addCriterion("legal_representative >=", value, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeLessThan(String value) {
            addCriterion("legal_representative <", value, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeLessThanOrEqualTo(String value) {
            addCriterion("legal_representative <=", value, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeLike(String value) {
            addCriterion("legal_representative like", value, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeNotLike(String value) {
            addCriterion("legal_representative not like", value, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeIn(List<String> values) {
            addCriterion("legal_representative in", values, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeNotIn(List<String> values) {
            addCriterion("legal_representative not in", values, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeBetween(String value1, String value2) {
            addCriterion("legal_representative between", value1, value2, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andLegalRepresentativeNotBetween(String value1, String value2) {
            addCriterion("legal_representative not between", value1, value2, "legalRepresentative");
            return (Criteria) this;
        }

        public Criteria andAttorneyIsNull() {
            addCriterion("attorney is null");
            return (Criteria) this;
        }

        public Criteria andAttorneyIsNotNull() {
            addCriterion("attorney is not null");
            return (Criteria) this;
        }

        public Criteria andAttorneyEqualTo(String value) {
            addCriterion("attorney =", value, "attorney");
            return (Criteria) this;
        }

        public Criteria andAttorneyNotEqualTo(String value) {
            addCriterion("attorney <>", value, "attorney");
            return (Criteria) this;
        }

        public Criteria andAttorneyGreaterThan(String value) {
            addCriterion("attorney >", value, "attorney");
            return (Criteria) this;
        }

        public Criteria andAttorneyGreaterThanOrEqualTo(String value) {
            addCriterion("attorney >=", value, "attorney");
            return (Criteria) this;
        }

        public Criteria andAttorneyLessThan(String value) {
            addCriterion("attorney <", value, "attorney");
            return (Criteria) this;
        }

        public Criteria andAttorneyLessThanOrEqualTo(String value) {
            addCriterion("attorney <=", value, "attorney");
            return (Criteria) this;
        }

        public Criteria andAttorneyLike(String value) {
            addCriterion("attorney like", value, "attorney");
            return (Criteria) this;
        }

        public Criteria andAttorneyNotLike(String value) {
            addCriterion("attorney not like", value, "attorney");
            return (Criteria) this;
        }

        public Criteria andAttorneyIn(List<String> values) {
            addCriterion("attorney in", values, "attorney");
            return (Criteria) this;
        }

        public Criteria andAttorneyNotIn(List<String> values) {
            addCriterion("attorney not in", values, "attorney");
            return (Criteria) this;
        }

        public Criteria andAttorneyBetween(String value1, String value2) {
            addCriterion("attorney between", value1, value2, "attorney");
            return (Criteria) this;
        }

        public Criteria andAttorneyNotBetween(String value1, String value2) {
            addCriterion("attorney not between", value1, value2, "attorney");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1IsNull() {
            addCriterion("mobile_phone1 is null");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1IsNotNull() {
            addCriterion("mobile_phone1 is not null");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1EqualTo(String value) {
            addCriterion("mobile_phone1 =", value, "mobilePhone1");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1NotEqualTo(String value) {
            addCriterion("mobile_phone1 <>", value, "mobilePhone1");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1GreaterThan(String value) {
            addCriterion("mobile_phone1 >", value, "mobilePhone1");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1GreaterThanOrEqualTo(String value) {
            addCriterion("mobile_phone1 >=", value, "mobilePhone1");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1LessThan(String value) {
            addCriterion("mobile_phone1 <", value, "mobilePhone1");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1LessThanOrEqualTo(String value) {
            addCriterion("mobile_phone1 <=", value, "mobilePhone1");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1Like(String value) {
            addCriterion("mobile_phone1 like", value, "mobilePhone1");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1NotLike(String value) {
            addCriterion("mobile_phone1 not like", value, "mobilePhone1");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1In(List<String> values) {
            addCriterion("mobile_phone1 in", values, "mobilePhone1");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1NotIn(List<String> values) {
            addCriterion("mobile_phone1 not in", values, "mobilePhone1");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1Between(String value1, String value2) {
            addCriterion("mobile_phone1 between", value1, value2, "mobilePhone1");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1NotBetween(String value1, String value2) {
            addCriterion("mobile_phone1 not between", value1, value2, "mobilePhone1");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1NameIsNull() {
            addCriterion("mobile_phone1_name is null");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1NameIsNotNull() {
            addCriterion("mobile_phone1_name is not null");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1NameEqualTo(String value) {
            addCriterion("mobile_phone1_name =", value, "mobilePhone1Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1NameNotEqualTo(String value) {
            addCriterion("mobile_phone1_name <>", value, "mobilePhone1Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1NameGreaterThan(String value) {
            addCriterion("mobile_phone1_name >", value, "mobilePhone1Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1NameGreaterThanOrEqualTo(String value) {
            addCriterion("mobile_phone1_name >=", value, "mobilePhone1Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1NameLessThan(String value) {
            addCriterion("mobile_phone1_name <", value, "mobilePhone1Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1NameLessThanOrEqualTo(String value) {
            addCriterion("mobile_phone1_name <=", value, "mobilePhone1Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1NameLike(String value) {
            addCriterion("mobile_phone1_name like", value, "mobilePhone1Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1NameNotLike(String value) {
            addCriterion("mobile_phone1_name not like", value, "mobilePhone1Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1NameIn(List<String> values) {
            addCriterion("mobile_phone1_name in", values, "mobilePhone1Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1NameNotIn(List<String> values) {
            addCriterion("mobile_phone1_name not in", values, "mobilePhone1Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1NameBetween(String value1, String value2) {
            addCriterion("mobile_phone1_name between", value1, value2, "mobilePhone1Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone1NameNotBetween(String value1, String value2) {
            addCriterion("mobile_phone1_name not between", value1, value2, "mobilePhone1Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2IsNull() {
            addCriterion("mobile_phone2 is null");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2IsNotNull() {
            addCriterion("mobile_phone2 is not null");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2EqualTo(String value) {
            addCriterion("mobile_phone2 =", value, "mobilePhone2");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2NotEqualTo(String value) {
            addCriterion("mobile_phone2 <>", value, "mobilePhone2");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2GreaterThan(String value) {
            addCriterion("mobile_phone2 >", value, "mobilePhone2");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2GreaterThanOrEqualTo(String value) {
            addCriterion("mobile_phone2 >=", value, "mobilePhone2");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2LessThan(String value) {
            addCriterion("mobile_phone2 <", value, "mobilePhone2");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2LessThanOrEqualTo(String value) {
            addCriterion("mobile_phone2 <=", value, "mobilePhone2");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2Like(String value) {
            addCriterion("mobile_phone2 like", value, "mobilePhone2");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2NotLike(String value) {
            addCriterion("mobile_phone2 not like", value, "mobilePhone2");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2In(List<String> values) {
            addCriterion("mobile_phone2 in", values, "mobilePhone2");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2NotIn(List<String> values) {
            addCriterion("mobile_phone2 not in", values, "mobilePhone2");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2Between(String value1, String value2) {
            addCriterion("mobile_phone2 between", value1, value2, "mobilePhone2");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2NotBetween(String value1, String value2) {
            addCriterion("mobile_phone2 not between", value1, value2, "mobilePhone2");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2NameIsNull() {
            addCriterion("mobile_phone2_name is null");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2NameIsNotNull() {
            addCriterion("mobile_phone2_name is not null");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2NameEqualTo(String value) {
            addCriterion("mobile_phone2_name =", value, "mobilePhone2Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2NameNotEqualTo(String value) {
            addCriterion("mobile_phone2_name <>", value, "mobilePhone2Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2NameGreaterThan(String value) {
            addCriterion("mobile_phone2_name >", value, "mobilePhone2Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2NameGreaterThanOrEqualTo(String value) {
            addCriterion("mobile_phone2_name >=", value, "mobilePhone2Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2NameLessThan(String value) {
            addCriterion("mobile_phone2_name <", value, "mobilePhone2Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2NameLessThanOrEqualTo(String value) {
            addCriterion("mobile_phone2_name <=", value, "mobilePhone2Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2NameLike(String value) {
            addCriterion("mobile_phone2_name like", value, "mobilePhone2Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2NameNotLike(String value) {
            addCriterion("mobile_phone2_name not like", value, "mobilePhone2Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2NameIn(List<String> values) {
            addCriterion("mobile_phone2_name in", values, "mobilePhone2Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2NameNotIn(List<String> values) {
            addCriterion("mobile_phone2_name not in", values, "mobilePhone2Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2NameBetween(String value1, String value2) {
            addCriterion("mobile_phone2_name between", value1, value2, "mobilePhone2Name");
            return (Criteria) this;
        }

        public Criteria andMobilePhone2NameNotBetween(String value1, String value2) {
            addCriterion("mobile_phone2_name not between", value1, value2, "mobilePhone2Name");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneIsNull() {
            addCriterion("fixed_telephone is null");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneIsNotNull() {
            addCriterion("fixed_telephone is not null");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneEqualTo(String value) {
            addCriterion("fixed_telephone =", value, "fixedTelephone");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneNotEqualTo(String value) {
            addCriterion("fixed_telephone <>", value, "fixedTelephone");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneGreaterThan(String value) {
            addCriterion("fixed_telephone >", value, "fixedTelephone");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneGreaterThanOrEqualTo(String value) {
            addCriterion("fixed_telephone >=", value, "fixedTelephone");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneLessThan(String value) {
            addCriterion("fixed_telephone <", value, "fixedTelephone");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneLessThanOrEqualTo(String value) {
            addCriterion("fixed_telephone <=", value, "fixedTelephone");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneLike(String value) {
            addCriterion("fixed_telephone like", value, "fixedTelephone");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneNotLike(String value) {
            addCriterion("fixed_telephone not like", value, "fixedTelephone");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneIn(List<String> values) {
            addCriterion("fixed_telephone in", values, "fixedTelephone");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneNotIn(List<String> values) {
            addCriterion("fixed_telephone not in", values, "fixedTelephone");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneBetween(String value1, String value2) {
            addCriterion("fixed_telephone between", value1, value2, "fixedTelephone");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneNotBetween(String value1, String value2) {
            addCriterion("fixed_telephone not between", value1, value2, "fixedTelephone");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneNameIsNull() {
            addCriterion("fixed_telephone_name is null");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneNameIsNotNull() {
            addCriterion("fixed_telephone_name is not null");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneNameEqualTo(String value) {
            addCriterion("fixed_telephone_name =", value, "fixedTelephoneName");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneNameNotEqualTo(String value) {
            addCriterion("fixed_telephone_name <>", value, "fixedTelephoneName");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneNameGreaterThan(String value) {
            addCriterion("fixed_telephone_name >", value, "fixedTelephoneName");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneNameGreaterThanOrEqualTo(String value) {
            addCriterion("fixed_telephone_name >=", value, "fixedTelephoneName");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneNameLessThan(String value) {
            addCriterion("fixed_telephone_name <", value, "fixedTelephoneName");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneNameLessThanOrEqualTo(String value) {
            addCriterion("fixed_telephone_name <=", value, "fixedTelephoneName");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneNameLike(String value) {
            addCriterion("fixed_telephone_name like", value, "fixedTelephoneName");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneNameNotLike(String value) {
            addCriterion("fixed_telephone_name not like", value, "fixedTelephoneName");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneNameIn(List<String> values) {
            addCriterion("fixed_telephone_name in", values, "fixedTelephoneName");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneNameNotIn(List<String> values) {
            addCriterion("fixed_telephone_name not in", values, "fixedTelephoneName");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneNameBetween(String value1, String value2) {
            addCriterion("fixed_telephone_name between", value1, value2, "fixedTelephoneName");
            return (Criteria) this;
        }

        public Criteria andFixedTelephoneNameNotBetween(String value1, String value2) {
            addCriterion("fixed_telephone_name not between", value1, value2, "fixedTelephoneName");
            return (Criteria) this;
        }

        public Criteria andBasicSigningDateIsNull() {
            addCriterion("basic_signing_date is null");
            return (Criteria) this;
        }

        public Criteria andBasicSigningDateIsNotNull() {
            addCriterion("basic_signing_date is not null");
            return (Criteria) this;
        }

        public Criteria andBasicSigningDateEqualTo(Date value) {
            addCriterionForJDBCDate("basic_signing_date =", value, "basicSigningDate");
            return (Criteria) this;
        }

        public Criteria andBasicSigningDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("basic_signing_date <>", value, "basicSigningDate");
            return (Criteria) this;
        }

        public Criteria andBasicSigningDateGreaterThan(Date value) {
            addCriterionForJDBCDate("basic_signing_date >", value, "basicSigningDate");
            return (Criteria) this;
        }

        public Criteria andBasicSigningDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("basic_signing_date >=", value, "basicSigningDate");
            return (Criteria) this;
        }

        public Criteria andBasicSigningDateLessThan(Date value) {
            addCriterionForJDBCDate("basic_signing_date <", value, "basicSigningDate");
            return (Criteria) this;
        }

        public Criteria andBasicSigningDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("basic_signing_date <=", value, "basicSigningDate");
            return (Criteria) this;
        }

        public Criteria andBasicSigningDateIn(List<Date> values) {
            addCriterionForJDBCDate("basic_signing_date in", values, "basicSigningDate");
            return (Criteria) this;
        }

        public Criteria andBasicSigningDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("basic_signing_date not in", values, "basicSigningDate");
            return (Criteria) this;
        }

        public Criteria andBasicSigningDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("basic_signing_date between", value1, value2, "basicSigningDate");
            return (Criteria) this;
        }

        public Criteria andBasicSigningDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("basic_signing_date not between", value1, value2, "basicSigningDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ledger_contract_supply_info
     *
     * @mbggenerated do_not_delete_during_merge Tue Oct 13 14:09:18 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ledger_contract_supply_info
     *
     * @mbggenerated Tue Oct 13 14:09:18 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}