package net.shopin.ledger.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class LedgerContractExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ledger_contract
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ledger_contract
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ledger_contract
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    public LedgerContractExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger_contract
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ledger_contract
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSettlementStatusIsNull() {
            addCriterion("settlement_status is null");
            return (Criteria) this;
        }

        public Criteria andSettlementStatusIsNotNull() {
            addCriterion("settlement_status is not null");
            return (Criteria) this;
        }

        public Criteria andSettlementStatusEqualTo(String value) {
            addCriterion("settlement_status =", value, "settlementStatus");
            return (Criteria) this;
        }

        public Criteria andSettlementStatusNotEqualTo(String value) {
            addCriterion("settlement_status <>", value, "settlementStatus");
            return (Criteria) this;
        }

        public Criteria andSettlementStatusGreaterThan(String value) {
            addCriterion("settlement_status >", value, "settlementStatus");
            return (Criteria) this;
        }

        public Criteria andSettlementStatusGreaterThanOrEqualTo(String value) {
            addCriterion("settlement_status >=", value, "settlementStatus");
            return (Criteria) this;
        }

        public Criteria andSettlementStatusLessThan(String value) {
            addCriterion("settlement_status <", value, "settlementStatus");
            return (Criteria) this;
        }

        public Criteria andSettlementStatusLessThanOrEqualTo(String value) {
            addCriterion("settlement_status <=", value, "settlementStatus");
            return (Criteria) this;
        }

        public Criteria andSettlementStatusLike(String value) {
            addCriterion("settlement_status like", value, "settlementStatus");
            return (Criteria) this;
        }

        public Criteria andSettlementStatusNotLike(String value) {
            addCriterion("settlement_status not like", value, "settlementStatus");
            return (Criteria) this;
        }

        public Criteria andSettlementStatusIn(List<String> values) {
            addCriterion("settlement_status in", values, "settlementStatus");
            return (Criteria) this;
        }

        public Criteria andSettlementStatusNotIn(List<String> values) {
            addCriterion("settlement_status not in", values, "settlementStatus");
            return (Criteria) this;
        }

        public Criteria andSettlementStatusBetween(String value1, String value2) {
            addCriterion("settlement_status between", value1, value2, "settlementStatus");
            return (Criteria) this;
        }

        public Criteria andSettlementStatusNotBetween(String value1, String value2) {
            addCriterion("settlement_status not between", value1, value2, "settlementStatus");
            return (Criteria) this;
        }

        public Criteria andCabinetStatusIsNull() {
            addCriterion("cabinet_status is null");
            return (Criteria) this;
        }

        public Criteria andCabinetStatusIsNotNull() {
            addCriterion("cabinet_status is not null");
            return (Criteria) this;
        }

        public Criteria andCabinetStatusEqualTo(String value) {
            addCriterion("cabinet_status =", value, "cabinetStatus");
            return (Criteria) this;
        }

        public Criteria andCabinetStatusNotEqualTo(String value) {
            addCriterion("cabinet_status <>", value, "cabinetStatus");
            return (Criteria) this;
        }

        public Criteria andCabinetStatusGreaterThan(String value) {
            addCriterion("cabinet_status >", value, "cabinetStatus");
            return (Criteria) this;
        }

        public Criteria andCabinetStatusGreaterThanOrEqualTo(String value) {
            addCriterion("cabinet_status >=", value, "cabinetStatus");
            return (Criteria) this;
        }

        public Criteria andCabinetStatusLessThan(String value) {
            addCriterion("cabinet_status <", value, "cabinetStatus");
            return (Criteria) this;
        }

        public Criteria andCabinetStatusLessThanOrEqualTo(String value) {
            addCriterion("cabinet_status <=", value, "cabinetStatus");
            return (Criteria) this;
        }

        public Criteria andCabinetStatusLike(String value) {
            addCriterion("cabinet_status like", value, "cabinetStatus");
            return (Criteria) this;
        }

        public Criteria andCabinetStatusNotLike(String value) {
            addCriterion("cabinet_status not like", value, "cabinetStatus");
            return (Criteria) this;
        }

        public Criteria andCabinetStatusIn(List<String> values) {
            addCriterion("cabinet_status in", values, "cabinetStatus");
            return (Criteria) this;
        }

        public Criteria andCabinetStatusNotIn(List<String> values) {
            addCriterion("cabinet_status not in", values, "cabinetStatus");
            return (Criteria) this;
        }

        public Criteria andCabinetStatusBetween(String value1, String value2) {
            addCriterion("cabinet_status between", value1, value2, "cabinetStatus");
            return (Criteria) this;
        }

        public Criteria andCabinetStatusNotBetween(String value1, String value2) {
            addCriterion("cabinet_status not between", value1, value2, "cabinetStatus");
            return (Criteria) this;
        }

        public Criteria andCabinetDateIsNull() {
            addCriterion("cabinet_date is null");
            return (Criteria) this;
        }

        public Criteria andCabinetDateIsNotNull() {
            addCriterion("cabinet_date is not null");
            return (Criteria) this;
        }

        public Criteria andCabinetDateEqualTo(Date value) {
            addCriterionForJDBCDate("cabinet_date =", value, "cabinetDate");
            return (Criteria) this;
        }

        public Criteria andCabinetDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("cabinet_date <>", value, "cabinetDate");
            return (Criteria) this;
        }

        public Criteria andCabinetDateGreaterThan(Date value) {
            addCriterionForJDBCDate("cabinet_date >", value, "cabinetDate");
            return (Criteria) this;
        }

        public Criteria andCabinetDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("cabinet_date >=", value, "cabinetDate");
            return (Criteria) this;
        }

        public Criteria andCabinetDateLessThan(Date value) {
            addCriterionForJDBCDate("cabinet_date <", value, "cabinetDate");
            return (Criteria) this;
        }

        public Criteria andCabinetDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("cabinet_date <=", value, "cabinetDate");
            return (Criteria) this;
        }

        public Criteria andCabinetDateIn(List<Date> values) {
            addCriterionForJDBCDate("cabinet_date in", values, "cabinetDate");
            return (Criteria) this;
        }

        public Criteria andCabinetDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("cabinet_date not in", values, "cabinetDate");
            return (Criteria) this;
        }

        public Criteria andCabinetDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("cabinet_date between", value1, value2, "cabinetDate");
            return (Criteria) this;
        }

        public Criteria andCabinetDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("cabinet_date not between", value1, value2, "cabinetDate");
            return (Criteria) this;
        }

        public Criteria andSignMarkIsNull() {
            addCriterion("sign_mark is null");
            return (Criteria) this;
        }

        public Criteria andSignMarkIsNotNull() {
            addCriterion("sign_mark is not null");
            return (Criteria) this;
        }

        public Criteria andSignMarkEqualTo(String value) {
            addCriterion("sign_mark =", value, "signMark");
            return (Criteria) this;
        }

        public Criteria andSignMarkNotEqualTo(String value) {
            addCriterion("sign_mark <>", value, "signMark");
            return (Criteria) this;
        }

        public Criteria andSignMarkGreaterThan(String value) {
            addCriterion("sign_mark >", value, "signMark");
            return (Criteria) this;
        }

        public Criteria andSignMarkGreaterThanOrEqualTo(String value) {
            addCriterion("sign_mark >=", value, "signMark");
            return (Criteria) this;
        }

        public Criteria andSignMarkLessThan(String value) {
            addCriterion("sign_mark <", value, "signMark");
            return (Criteria) this;
        }

        public Criteria andSignMarkLessThanOrEqualTo(String value) {
            addCriterion("sign_mark <=", value, "signMark");
            return (Criteria) this;
        }

        public Criteria andSignMarkLike(String value) {
            addCriterion("sign_mark like", value, "signMark");
            return (Criteria) this;
        }

        public Criteria andSignMarkNotLike(String value) {
            addCriterion("sign_mark not like", value, "signMark");
            return (Criteria) this;
        }

        public Criteria andSignMarkIn(List<String> values) {
            addCriterion("sign_mark in", values, "signMark");
            return (Criteria) this;
        }

        public Criteria andSignMarkNotIn(List<String> values) {
            addCriterion("sign_mark not in", values, "signMark");
            return (Criteria) this;
        }

        public Criteria andSignMarkBetween(String value1, String value2) {
            addCriterion("sign_mark between", value1, value2, "signMark");
            return (Criteria) this;
        }

        public Criteria andSignMarkNotBetween(String value1, String value2) {
            addCriterion("sign_mark not between", value1, value2, "signMark");
            return (Criteria) this;
        }

        public Criteria andAuthorizedStartDateIsNull() {
            addCriterion("authorized_start_date is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizedStartDateIsNotNull() {
            addCriterion("authorized_start_date is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizedStartDateEqualTo(Date value) {
            addCriterionForJDBCDate("authorized_start_date =", value, "authorizedStartDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedStartDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("authorized_start_date <>", value, "authorizedStartDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedStartDateGreaterThan(Date value) {
            addCriterionForJDBCDate("authorized_start_date >", value, "authorizedStartDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedStartDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("authorized_start_date >=", value, "authorizedStartDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedStartDateLessThan(Date value) {
            addCriterionForJDBCDate("authorized_start_date <", value, "authorizedStartDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedStartDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("authorized_start_date <=", value, "authorizedStartDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedStartDateIn(List<Date> values) {
            addCriterionForJDBCDate("authorized_start_date in", values, "authorizedStartDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedStartDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("authorized_start_date not in", values, "authorizedStartDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedStartDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("authorized_start_date between", value1, value2, "authorizedStartDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedStartDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("authorized_start_date not between", value1, value2, "authorizedStartDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEndDateIsNull() {
            addCriterion("authorized_end_date is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEndDateIsNotNull() {
            addCriterion("authorized_end_date is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEndDateEqualTo(Date value) {
            addCriterionForJDBCDate("authorized_end_date =", value, "authorizedEndDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEndDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("authorized_end_date <>", value, "authorizedEndDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEndDateGreaterThan(Date value) {
            addCriterionForJDBCDate("authorized_end_date >", value, "authorizedEndDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEndDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("authorized_end_date >=", value, "authorizedEndDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEndDateLessThan(Date value) {
            addCriterionForJDBCDate("authorized_end_date <", value, "authorizedEndDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEndDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("authorized_end_date <=", value, "authorizedEndDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEndDateIn(List<Date> values) {
            addCriterionForJDBCDate("authorized_end_date in", values, "authorizedEndDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEndDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("authorized_end_date not in", values, "authorizedEndDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEndDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("authorized_end_date between", value1, value2, "authorizedEndDate");
            return (Criteria) this;
        }

        public Criteria andAuthorizedEndDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("authorized_end_date not between", value1, value2, "authorizedEndDate");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeIsNull() {
            addCriterion("supplier_code is null");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeIsNotNull() {
            addCriterion("supplier_code is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeEqualTo(String value) {
            addCriterion("supplier_code =", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeNotEqualTo(String value) {
            addCriterion("supplier_code <>", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeGreaterThan(String value) {
            addCriterion("supplier_code >", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeGreaterThanOrEqualTo(String value) {
            addCriterion("supplier_code >=", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeLessThan(String value) {
            addCriterion("supplier_code <", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeLessThanOrEqualTo(String value) {
            addCriterion("supplier_code <=", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeLike(String value) {
            addCriterion("supplier_code like", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeNotLike(String value) {
            addCriterion("supplier_code not like", value, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeIn(List<String> values) {
            addCriterion("supplier_code in", values, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeNotIn(List<String> values) {
            addCriterion("supplier_code not in", values, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeBetween(String value1, String value2) {
            addCriterion("supplier_code between", value1, value2, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andSupplierCodeNotBetween(String value1, String value2) {
            addCriterion("supplier_code not between", value1, value2, "supplierCode");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("category is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("category is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(String value) {
            addCriterion("category =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(String value) {
            addCriterion("category <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(String value) {
            addCriterion("category >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("category >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(String value) {
            addCriterion("category <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(String value) {
            addCriterion("category <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLike(String value) {
            addCriterion("category like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotLike(String value) {
            addCriterion("category not like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<String> values) {
            addCriterion("category in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<String> values) {
            addCriterion("category not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(String value1, String value2) {
            addCriterion("category between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(String value1, String value2) {
            addCriterion("category not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andBrandNameIsNull() {
            addCriterion("brand_name is null");
            return (Criteria) this;
        }

        public Criteria andBrandNameIsNotNull() {
            addCriterion("brand_name is not null");
            return (Criteria) this;
        }

        public Criteria andBrandNameEqualTo(String value) {
            addCriterion("brand_name =", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotEqualTo(String value) {
            addCriterion("brand_name <>", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameGreaterThan(String value) {
            addCriterion("brand_name >", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameGreaterThanOrEqualTo(String value) {
            addCriterion("brand_name >=", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLessThan(String value) {
            addCriterion("brand_name <", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLessThanOrEqualTo(String value) {
            addCriterion("brand_name <=", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLike(String value) {
            addCriterion("brand_name like", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotLike(String value) {
            addCriterion("brand_name not like", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameIn(List<String> values) {
            addCriterion("brand_name in", values, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotIn(List<String> values) {
            addCriterion("brand_name not in", values, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameBetween(String value1, String value2) {
            addCriterion("brand_name between", value1, value2, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotBetween(String value1, String value2) {
            addCriterion("brand_name not between", value1, value2, "brandName");
            return (Criteria) this;
        }

        public Criteria andStoreEncodingIsNull() {
            addCriterion("store_encoding is null");
            return (Criteria) this;
        }

        public Criteria andStoreEncodingIsNotNull() {
            addCriterion("store_encoding is not null");
            return (Criteria) this;
        }

        public Criteria andStoreEncodingEqualTo(String value) {
            addCriterion("store_encoding =", value, "storeEncoding");
            return (Criteria) this;
        }

        public Criteria andStoreEncodingNotEqualTo(String value) {
            addCriterion("store_encoding <>", value, "storeEncoding");
            return (Criteria) this;
        }

        public Criteria andStoreEncodingGreaterThan(String value) {
            addCriterion("store_encoding >", value, "storeEncoding");
            return (Criteria) this;
        }

        public Criteria andStoreEncodingGreaterThanOrEqualTo(String value) {
            addCriterion("store_encoding >=", value, "storeEncoding");
            return (Criteria) this;
        }

        public Criteria andStoreEncodingLessThan(String value) {
            addCriterion("store_encoding <", value, "storeEncoding");
            return (Criteria) this;
        }

        public Criteria andStoreEncodingLessThanOrEqualTo(String value) {
            addCriterion("store_encoding <=", value, "storeEncoding");
            return (Criteria) this;
        }

        public Criteria andStoreEncodingLike(String value) {
            addCriterion("store_encoding like", value, "storeEncoding");
            return (Criteria) this;
        }

        public Criteria andStoreEncodingNotLike(String value) {
            addCriterion("store_encoding not like", value, "storeEncoding");
            return (Criteria) this;
        }

        public Criteria andStoreEncodingIn(List<String> values) {
            addCriterion("store_encoding in", values, "storeEncoding");
            return (Criteria) this;
        }

        public Criteria andStoreEncodingNotIn(List<String> values) {
            addCriterion("store_encoding not in", values, "storeEncoding");
            return (Criteria) this;
        }

        public Criteria andStoreEncodingBetween(String value1, String value2) {
            addCriterion("store_encoding between", value1, value2, "storeEncoding");
            return (Criteria) this;
        }

        public Criteria andStoreEncodingNotBetween(String value1, String value2) {
            addCriterion("store_encoding not between", value1, value2, "storeEncoding");
            return (Criteria) this;
        }

        public Criteria andStoreNameIsNull() {
            addCriterion("store_name is null");
            return (Criteria) this;
        }

        public Criteria andStoreNameIsNotNull() {
            addCriterion("store_name is not null");
            return (Criteria) this;
        }

        public Criteria andStoreNameEqualTo(String value) {
            addCriterion("store_name =", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotEqualTo(String value) {
            addCriterion("store_name <>", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameGreaterThan(String value) {
            addCriterion("store_name >", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameGreaterThanOrEqualTo(String value) {
            addCriterion("store_name >=", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameLessThan(String value) {
            addCriterion("store_name <", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameLessThanOrEqualTo(String value) {
            addCriterion("store_name <=", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameLike(String value) {
            addCriterion("store_name like", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotLike(String value) {
            addCriterion("store_name not like", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameIn(List<String> values) {
            addCriterion("store_name in", values, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotIn(List<String> values) {
            addCriterion("store_name not in", values, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameBetween(String value1, String value2) {
            addCriterion("store_name between", value1, value2, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotBetween(String value1, String value2) {
            addCriterion("store_name not between", value1, value2, "storeName");
            return (Criteria) this;
        }

        public Criteria andDeductionRateIsNull() {
            addCriterion("deduction_rate is null");
            return (Criteria) this;
        }

        public Criteria andDeductionRateIsNotNull() {
            addCriterion("deduction_rate is not null");
            return (Criteria) this;
        }

        public Criteria andDeductionRateEqualTo(Double value) {
            addCriterion("deduction_rate =", value, "deductionRate");
            return (Criteria) this;
        }

        public Criteria andDeductionRateNotEqualTo(Double value) {
            addCriterion("deduction_rate <>", value, "deductionRate");
            return (Criteria) this;
        }

        public Criteria andDeductionRateGreaterThan(Double value) {
            addCriterion("deduction_rate >", value, "deductionRate");
            return (Criteria) this;
        }

        public Criteria andDeductionRateGreaterThanOrEqualTo(Double value) {
            addCriterion("deduction_rate >=", value, "deductionRate");
            return (Criteria) this;
        }

        public Criteria andDeductionRateLessThan(Double value) {
            addCriterion("deduction_rate <", value, "deductionRate");
            return (Criteria) this;
        }

        public Criteria andDeductionRateLessThanOrEqualTo(Double value) {
            addCriterion("deduction_rate <=", value, "deductionRate");
            return (Criteria) this;
        }

        public Criteria andDeductionRateIn(List<Double> values) {
            addCriterion("deduction_rate in", values, "deductionRate");
            return (Criteria) this;
        }

        public Criteria andDeductionRateNotIn(List<Double> values) {
            addCriterion("deduction_rate not in", values, "deductionRate");
            return (Criteria) this;
        }

        public Criteria andDeductionRateBetween(Double value1, Double value2) {
            addCriterion("deduction_rate between", value1, value2, "deductionRate");
            return (Criteria) this;
        }

        public Criteria andDeductionRateNotBetween(Double value1, Double value2) {
            addCriterion("deduction_rate not between", value1, value2, "deductionRate");
            return (Criteria) this;
        }

        public Criteria andAssessmentIndicatorIsNull() {
            addCriterion("assessment_indicator is null");
            return (Criteria) this;
        }

        public Criteria andAssessmentIndicatorIsNotNull() {
            addCriterion("assessment_indicator is not null");
            return (Criteria) this;
        }

        public Criteria andAssessmentIndicatorEqualTo(String value) {
            addCriterion("assessment_indicator =", value, "assessmentIndicator");
            return (Criteria) this;
        }

        public Criteria andAssessmentIndicatorNotEqualTo(String value) {
            addCriterion("assessment_indicator <>", value, "assessmentIndicator");
            return (Criteria) this;
        }

        public Criteria andAssessmentIndicatorGreaterThan(String value) {
            addCriterion("assessment_indicator >", value, "assessmentIndicator");
            return (Criteria) this;
        }

        public Criteria andAssessmentIndicatorGreaterThanOrEqualTo(String value) {
            addCriterion("assessment_indicator >=", value, "assessmentIndicator");
            return (Criteria) this;
        }

        public Criteria andAssessmentIndicatorLessThan(String value) {
            addCriterion("assessment_indicator <", value, "assessmentIndicator");
            return (Criteria) this;
        }

        public Criteria andAssessmentIndicatorLessThanOrEqualTo(String value) {
            addCriterion("assessment_indicator <=", value, "assessmentIndicator");
            return (Criteria) this;
        }

        public Criteria andAssessmentIndicatorLike(String value) {
            addCriterion("assessment_indicator like", value, "assessmentIndicator");
            return (Criteria) this;
        }

        public Criteria andAssessmentIndicatorNotLike(String value) {
            addCriterion("assessment_indicator not like", value, "assessmentIndicator");
            return (Criteria) this;
        }

        public Criteria andAssessmentIndicatorIn(List<String> values) {
            addCriterion("assessment_indicator in", values, "assessmentIndicator");
            return (Criteria) this;
        }

        public Criteria andAssessmentIndicatorNotIn(List<String> values) {
            addCriterion("assessment_indicator not in", values, "assessmentIndicator");
            return (Criteria) this;
        }

        public Criteria andAssessmentIndicatorBetween(String value1, String value2) {
            addCriterion("assessment_indicator between", value1, value2, "assessmentIndicator");
            return (Criteria) this;
        }

        public Criteria andAssessmentIndicatorNotBetween(String value1, String value2) {
            addCriterion("assessment_indicator not between", value1, value2, "assessmentIndicator");
            return (Criteria) this;
        }

        public Criteria andSigningDateIsNull() {
            addCriterion("signing_date is null");
            return (Criteria) this;
        }

        public Criteria andSigningDateIsNotNull() {
            addCriterion("signing_date is not null");
            return (Criteria) this;
        }

        public Criteria andSigningDateEqualTo(Date value) {
            addCriterionForJDBCDate("signing_date =", value, "signingDate");
            return (Criteria) this;
        }

        public Criteria andSigningDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("signing_date <>", value, "signingDate");
            return (Criteria) this;
        }

        public Criteria andSigningDateGreaterThan(Date value) {
            addCriterionForJDBCDate("signing_date >", value, "signingDate");
            return (Criteria) this;
        }

        public Criteria andSigningDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("signing_date >=", value, "signingDate");
            return (Criteria) this;
        }

        public Criteria andSigningDateLessThan(Date value) {
            addCriterionForJDBCDate("signing_date <", value, "signingDate");
            return (Criteria) this;
        }

        public Criteria andSigningDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("signing_date <=", value, "signingDate");
            return (Criteria) this;
        }

        public Criteria andSigningDateIn(List<Date> values) {
            addCriterionForJDBCDate("signing_date in", values, "signingDate");
            return (Criteria) this;
        }

        public Criteria andSigningDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("signing_date not in", values, "signingDate");
            return (Criteria) this;
        }

        public Criteria andSigningDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("signing_date between", value1, value2, "signingDate");
            return (Criteria) this;
        }

        public Criteria andSigningDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("signing_date not between", value1, value2, "signingDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("start_date is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("start_date is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(Date value) {
            addCriterionForJDBCDate("start_date =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("start_date <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(Date value) {
            addCriterionForJDBCDate("start_date >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("start_date >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(Date value) {
            addCriterionForJDBCDate("start_date <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("start_date <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<Date> values) {
            addCriterionForJDBCDate("start_date in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("start_date not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("start_date between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("start_date not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("end_date is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("end_date is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(Date value) {
            addCriterionForJDBCDate("end_date =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("end_date <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(Date value) {
            addCriterionForJDBCDate("end_date >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("end_date >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(Date value) {
            addCriterionForJDBCDate("end_date <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("end_date <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<Date> values) {
            addCriterionForJDBCDate("end_date in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("end_date not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("end_date between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("end_date not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andContractDeadlineIsNull() {
            addCriterion("contract_deadline is null");
            return (Criteria) this;
        }

        public Criteria andContractDeadlineIsNotNull() {
            addCriterion("contract_deadline is not null");
            return (Criteria) this;
        }

        public Criteria andContractDeadlineEqualTo(Date value) {
            addCriterionForJDBCDate("contract_deadline =", value, "contractDeadline");
            return (Criteria) this;
        }

        public Criteria andContractDeadlineNotEqualTo(Date value) {
            addCriterionForJDBCDate("contract_deadline <>", value, "contractDeadline");
            return (Criteria) this;
        }

        public Criteria andContractDeadlineGreaterThan(Date value) {
            addCriterionForJDBCDate("contract_deadline >", value, "contractDeadline");
            return (Criteria) this;
        }

        public Criteria andContractDeadlineGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("contract_deadline >=", value, "contractDeadline");
            return (Criteria) this;
        }

        public Criteria andContractDeadlineLessThan(Date value) {
            addCriterionForJDBCDate("contract_deadline <", value, "contractDeadline");
            return (Criteria) this;
        }

        public Criteria andContractDeadlineLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("contract_deadline <=", value, "contractDeadline");
            return (Criteria) this;
        }

        public Criteria andContractDeadlineIn(List<Date> values) {
            addCriterionForJDBCDate("contract_deadline in", values, "contractDeadline");
            return (Criteria) this;
        }

        public Criteria andContractDeadlineNotIn(List<Date> values) {
            addCriterionForJDBCDate("contract_deadline not in", values, "contractDeadline");
            return (Criteria) this;
        }

        public Criteria andContractDeadlineBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("contract_deadline between", value1, value2, "contractDeadline");
            return (Criteria) this;
        }

        public Criteria andContractDeadlineNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("contract_deadline not between", value1, value2, "contractDeadline");
            return (Criteria) this;
        }

        public Criteria andManagementFeesIsNull() {
            addCriterion("management_fees is null");
            return (Criteria) this;
        }

        public Criteria andManagementFeesIsNotNull() {
            addCriterion("management_fees is not null");
            return (Criteria) this;
        }

        public Criteria andManagementFeesEqualTo(Double value) {
            addCriterion("management_fees =", value, "managementFees");
            return (Criteria) this;
        }

        public Criteria andManagementFeesNotEqualTo(Double value) {
            addCriterion("management_fees <>", value, "managementFees");
            return (Criteria) this;
        }

        public Criteria andManagementFeesGreaterThan(Double value) {
            addCriterion("management_fees >", value, "managementFees");
            return (Criteria) this;
        }

        public Criteria andManagementFeesGreaterThanOrEqualTo(Double value) {
            addCriterion("management_fees >=", value, "managementFees");
            return (Criteria) this;
        }

        public Criteria andManagementFeesLessThan(Double value) {
            addCriterion("management_fees <", value, "managementFees");
            return (Criteria) this;
        }

        public Criteria andManagementFeesLessThanOrEqualTo(Double value) {
            addCriterion("management_fees <=", value, "managementFees");
            return (Criteria) this;
        }

        public Criteria andManagementFeesIn(List<Double> values) {
            addCriterion("management_fees in", values, "managementFees");
            return (Criteria) this;
        }

        public Criteria andManagementFeesNotIn(List<Double> values) {
            addCriterion("management_fees not in", values, "managementFees");
            return (Criteria) this;
        }

        public Criteria andManagementFeesBetween(Double value1, Double value2) {
            addCriterion("management_fees between", value1, value2, "managementFees");
            return (Criteria) this;
        }

        public Criteria andManagementFeesNotBetween(Double value1, Double value2) {
            addCriterion("management_fees not between", value1, value2, "managementFees");
            return (Criteria) this;
        }

        public Criteria andCardFeesIsNull() {
            addCriterion("card_fees is null");
            return (Criteria) this;
        }

        public Criteria andCardFeesIsNotNull() {
            addCriterion("card_fees is not null");
            return (Criteria) this;
        }

        public Criteria andCardFeesEqualTo(String value) {
            addCriterion("card_fees =", value, "cardFees");
            return (Criteria) this;
        }

        public Criteria andCardFeesNotEqualTo(String value) {
            addCriterion("card_fees <>", value, "cardFees");
            return (Criteria) this;
        }

        public Criteria andCardFeesGreaterThan(String value) {
            addCriterion("card_fees >", value, "cardFees");
            return (Criteria) this;
        }

        public Criteria andCardFeesGreaterThanOrEqualTo(String value) {
            addCriterion("card_fees >=", value, "cardFees");
            return (Criteria) this;
        }

        public Criteria andCardFeesLessThan(String value) {
            addCriterion("card_fees <", value, "cardFees");
            return (Criteria) this;
        }

        public Criteria andCardFeesLessThanOrEqualTo(String value) {
            addCriterion("card_fees <=", value, "cardFees");
            return (Criteria) this;
        }

        public Criteria andCardFeesLike(String value) {
            addCriterion("card_fees like", value, "cardFees");
            return (Criteria) this;
        }

        public Criteria andCardFeesNotLike(String value) {
            addCriterion("card_fees not like", value, "cardFees");
            return (Criteria) this;
        }

        public Criteria andCardFeesIn(List<String> values) {
            addCriterion("card_fees in", values, "cardFees");
            return (Criteria) this;
        }

        public Criteria andCardFeesNotIn(List<String> values) {
            addCriterion("card_fees not in", values, "cardFees");
            return (Criteria) this;
        }

        public Criteria andCardFeesBetween(String value1, String value2) {
            addCriterion("card_fees between", value1, value2, "cardFees");
            return (Criteria) this;
        }

        public Criteria andCardFeesNotBetween(String value1, String value2) {
            addCriterion("card_fees not between", value1, value2, "cardFees");
            return (Criteria) this;
        }

        public Criteria andContractVersionIsNull() {
            addCriterion("contract_version is null");
            return (Criteria) this;
        }

        public Criteria andContractVersionIsNotNull() {
            addCriterion("contract_version is not null");
            return (Criteria) this;
        }

        public Criteria andContractVersionEqualTo(String value) {
            addCriterion("contract_version =", value, "contractVersion");
            return (Criteria) this;
        }

        public Criteria andContractVersionNotEqualTo(String value) {
            addCriterion("contract_version <>", value, "contractVersion");
            return (Criteria) this;
        }

        public Criteria andContractVersionGreaterThan(String value) {
            addCriterion("contract_version >", value, "contractVersion");
            return (Criteria) this;
        }

        public Criteria andContractVersionGreaterThanOrEqualTo(String value) {
            addCriterion("contract_version >=", value, "contractVersion");
            return (Criteria) this;
        }

        public Criteria andContractVersionLessThan(String value) {
            addCriterion("contract_version <", value, "contractVersion");
            return (Criteria) this;
        }

        public Criteria andContractVersionLessThanOrEqualTo(String value) {
            addCriterion("contract_version <=", value, "contractVersion");
            return (Criteria) this;
        }

        public Criteria andContractVersionLike(String value) {
            addCriterion("contract_version like", value, "contractVersion");
            return (Criteria) this;
        }

        public Criteria andContractVersionNotLike(String value) {
            addCriterion("contract_version not like", value, "contractVersion");
            return (Criteria) this;
        }

        public Criteria andContractVersionIn(List<String> values) {
            addCriterion("contract_version in", values, "contractVersion");
            return (Criteria) this;
        }

        public Criteria andContractVersionNotIn(List<String> values) {
            addCriterion("contract_version not in", values, "contractVersion");
            return (Criteria) this;
        }

        public Criteria andContractVersionBetween(String value1, String value2) {
            addCriterion("contract_version between", value1, value2, "contractVersion");
            return (Criteria) this;
        }

        public Criteria andContractVersionNotBetween(String value1, String value2) {
            addCriterion("contract_version not between", value1, value2, "contractVersion");
            return (Criteria) this;
        }

        public Criteria andCheckTagIsNull() {
            addCriterion("check_tag is null");
            return (Criteria) this;
        }

        public Criteria andCheckTagIsNotNull() {
            addCriterion("check_tag is not null");
            return (Criteria) this;
        }

        public Criteria andCheckTagEqualTo(String value) {
            addCriterion("check_tag =", value, "checkTag");
            return (Criteria) this;
        }

        public Criteria andCheckTagNotEqualTo(String value) {
            addCriterion("check_tag <>", value, "checkTag");
            return (Criteria) this;
        }

        public Criteria andCheckTagGreaterThan(String value) {
            addCriterion("check_tag >", value, "checkTag");
            return (Criteria) this;
        }

        public Criteria andCheckTagGreaterThanOrEqualTo(String value) {
            addCriterion("check_tag >=", value, "checkTag");
            return (Criteria) this;
        }

        public Criteria andCheckTagLessThan(String value) {
            addCriterion("check_tag <", value, "checkTag");
            return (Criteria) this;
        }

        public Criteria andCheckTagLessThanOrEqualTo(String value) {
            addCriterion("check_tag <=", value, "checkTag");
            return (Criteria) this;
        }

        public Criteria andCheckTagLike(String value) {
            addCriterion("check_tag like", value, "checkTag");
            return (Criteria) this;
        }

        public Criteria andCheckTagNotLike(String value) {
            addCriterion("check_tag not like", value, "checkTag");
            return (Criteria) this;
        }

        public Criteria andCheckTagIn(List<String> values) {
            addCriterion("check_tag in", values, "checkTag");
            return (Criteria) this;
        }

        public Criteria andCheckTagNotIn(List<String> values) {
            addCriterion("check_tag not in", values, "checkTag");
            return (Criteria) this;
        }

        public Criteria andCheckTagBetween(String value1, String value2) {
            addCriterion("check_tag between", value1, value2, "checkTag");
            return (Criteria) this;
        }

        public Criteria andCheckTagNotBetween(String value1, String value2) {
            addCriterion("check_tag not between", value1, value2, "checkTag");
            return (Criteria) this;
        }

        public Criteria andCheckNameIsNull() {
            addCriterion("check_name is null");
            return (Criteria) this;
        }

        public Criteria andCheckNameIsNotNull() {
            addCriterion("check_name is not null");
            return (Criteria) this;
        }

        public Criteria andCheckNameEqualTo(String value) {
            addCriterion("check_name =", value, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameNotEqualTo(String value) {
            addCriterion("check_name <>", value, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameGreaterThan(String value) {
            addCriterion("check_name >", value, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameGreaterThanOrEqualTo(String value) {
            addCriterion("check_name >=", value, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameLessThan(String value) {
            addCriterion("check_name <", value, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameLessThanOrEqualTo(String value) {
            addCriterion("check_name <=", value, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameLike(String value) {
            addCriterion("check_name like", value, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameNotLike(String value) {
            addCriterion("check_name not like", value, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameIn(List<String> values) {
            addCriterion("check_name in", values, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameNotIn(List<String> values) {
            addCriterion("check_name not in", values, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameBetween(String value1, String value2) {
            addCriterion("check_name between", value1, value2, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckNameNotBetween(String value1, String value2) {
            addCriterion("check_name not between", value1, value2, "checkName");
            return (Criteria) this;
        }

        public Criteria andCheckDateIsNull() {
            addCriterion("check_date is null");
            return (Criteria) this;
        }

        public Criteria andCheckDateIsNotNull() {
            addCriterion("check_date is not null");
            return (Criteria) this;
        }

        public Criteria andCheckDateEqualTo(Date value) {
            addCriterionForJDBCDate("check_date =", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("check_date <>", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateGreaterThan(Date value) {
            addCriterionForJDBCDate("check_date >", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("check_date >=", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateLessThan(Date value) {
            addCriterionForJDBCDate("check_date <", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("check_date <=", value, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateIn(List<Date> values) {
            addCriterionForJDBCDate("check_date in", values, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("check_date not in", values, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("check_date between", value1, value2, "checkDate");
            return (Criteria) this;
        }

        public Criteria andCheckDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("check_date not between", value1, value2, "checkDate");
            return (Criteria) this;
        }

        public Criteria andValidIsNull() {
            addCriterion("valid is null");
            return (Criteria) this;
        }

        public Criteria andValidIsNotNull() {
            addCriterion("valid is not null");
            return (Criteria) this;
        }

        public Criteria andValidEqualTo(Boolean value) {
            addCriterion("valid =", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotEqualTo(Boolean value) {
            addCriterion("valid <>", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThan(Boolean value) {
            addCriterion("valid >", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThanOrEqualTo(Boolean value) {
            addCriterion("valid >=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThan(Boolean value) {
            addCriterion("valid <", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThanOrEqualTo(Boolean value) {
            addCriterion("valid <=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidIn(List<Boolean> values) {
            addCriterion("valid in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotIn(List<Boolean> values) {
            addCriterion("valid not in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidBetween(Boolean value1, Boolean value2) {
            addCriterion("valid between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotBetween(Boolean value1, Boolean value2) {
            addCriterion("valid not between", value1, value2, "valid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ledger_contract
     *
     * @mbggenerated do_not_delete_during_merge Mon Oct 19 19:26:19 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ledger_contract
     *
     * @mbggenerated Mon Oct 19 19:26:19 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}